### ISSUE TITLE
typo in the website

### ISSUE THREAD

**Issue by mmkaw** [giotiskl/Filterizr#1]
typo in the website document in "install div". it should be data-filter, instead of data-fltr. have attached image. it does not work with "data-fltr" attribute. or am i missing something?
![filterz](https://cloud.githubusercontent.com/assets/13604847/13397141/9dcaa47c-df1e-11e5-9709-25d0331df6cc.jpg)

**Comment by giotiskl** [comment]
You are absolutely right sir, it should be data-filter. I will correct it as soon as I am at home, thank you for the feedback.

**Comment by giotiskl** [comment]
It is now fixed, thanks again for the feedback
