### ISSUE TITLE
Can items not belong to multiple categories?

### ISSUE THREAD

**Issue by arkid** [giotiskl/Filterizr#10]
I can't find a way to make the plugin work with multiple categories.   Is this really not possible?  If so its a deal breaker for me and I'd love to see it added.

**Comment by mmkaw** [comment]
you can, in data-category attribute add coma to separate multiple categories. like data-category="1, 2"
data-category="1, 2, 3". is that what you are looking for? its shown in http://yiotis.net/filterizr/ > tutorials > install

**Comment by arkid** [comment]
Sorry yes of course, I will close this!
