### ISSUE TITLE
Callback function - not triggering

### ISSUE THREAD

**Issue by vijaykani** [giotiskl/filterizr#100]
I'm using latest version of Filterizr. But callback function which are funcation in documentation site, it is not working. Can you please help on this.

$(function() {
          var f = $('.filtr-container').filterizr({ 
           controlsSelector: '.fltr-controls',
           callbacks: {
                  onFilteringStart: function() {
                    alert("filter started");
                  },
                  onFilteringEnd: function() { },
                  onShufflingStart: function() { },
                  onShufflingEnd: function() { },
                  onSortingStart: function() { },
                  onSortingEnd: function() { }
               }
          });

**Comment by alr2413** [comment]
I have the same issue.
Inline callback functions within option array are not triggered but if you use the jquery method as mentioned in documents, it works perfectly.
Here is code:
`filtrizr.on('filteringStart', function() {
  alert("filter started");
})`

**Comment by swiftyone** [comment]
As a workaround you can listen for the events in the element. In your example it would be e.g.:
```
f.on('filteringStart.Filterizr', function () {
  console.log('filteringStart');
});

```

**Comment by giotiskl** [comment]
Should now be fixed in v2
