### ISSUE TITLE
Grids like Pinterest or Bootstrap 4 cards

### ISSUE THREAD

**Issue by ronaldaug** [giotiskl/Filterizr#101]
I try using bootstrap cards like this and it doesn't work.

```
<div class="card-columns filtr-container">
<div class="card one">
...
</div>
<div class="card two">
...
</div>
</div>
```

Is there any option for the grids like pinterest design?
Something like this..
<img src="https://s25005.pcdn.co/wp-content/uploads/2014/10/wookmark.jpg" width="60%" height="auto">

**Comment by giotiskl** [comment]
@ronaldaug you have to initialize your filterizr with the layout options set to `'packed'`:
````
var filterizr = $('.filter-container').filterizr({ layout: 'packed' });
````
