### ISSUE TITLE
Element not affected by filtering

### ISSUE THREAD

**Issue by sebastienwozny** [giotiskl/filterizr#104]
Hi guys,

I want to achieve something but I'm not sure it's possible.

I have a grid like this (with bootstrap4) :
[container filterized]
[img] [img] [img]
[img] [img] [img]
[img] [img] [add img button]
[/container]

Do you have any solution to make this button at the end always here and not filtered ?
For now my solution is to get all "tags" in my list and put them in the [add button] data attribute.

Thanks!

**Comment by giotiskl** [comment]
This would be essentially possible if your button is a regular item in the grid like all others and you set its data-category to be all categories, then no matter the active filter it would be visible
