### ISSUE TITLE
how can I change the loding animation and load custom animation

### ISSUE THREAD

**Issue by tonypius** [giotiskl/filterizr#110]

**Comment by giotiskl** [comment]
@tonypius since the latest version there is an `onInitCallback` provided in the options ([see documentation here](https://yiotis.net/filterizr/#/documentation/vanilla/onInit)). 

You can display a spinner and use this callback to hide it when your grid is ready to render.

**Comment by giotiskl** [comment]
Since the latest version (v2.2.0) there's an official built-in spinner animation, please consult https://yiotis.net/filterizr/#/documentation/vanilla/options
