### ISSUE TITLE
From another page I want to jump in specific filter URL

### ISSUE THREAD

**Issue by kaltrinemehmeti** [giotiskl/filterizr#114]
Im trying so many ways but than they doesnt work in IE, please can you suggest me something.
I have a page that from Home I want to go to the filter page but example 
www.home.com i click button that has Apartments with 2 guest filter --->

something like this
www.home/myapartment/?filter=2

**Comment by giotiskl** [comment]
You can simply parse the filter from the query parameter and initialize your Filterizr like this: $('container').filterizr({ filter: parsedFilter })
