### ISSUE TITLE
Multilevel filtering (or filter combination)

### ISSUE THREAD

**Issue by vicked** [giotiskl/filterizr#115]
Hi there!

First of all, I really like this library, thanks for your great work @giotiskl!

I wondering if multilevel filtering is possible? I have 3 filter group and the filter groups inside combined with 'or' operator but the groups combined with 'and'. I don't found any trivial way yet, am I missing something?

The use case:
Filters: F1-1, F1-2, F2-A, F2-B, F3-X, F3-Y
example items: item1(1, A, B, Y), item2(2, A), item3(1, B), item4(1, C, X), item5(2, B, Y)

case1: 
active filters: F1-1
visible items: item1, item3, item4

case2:
active filters: F1-1, F2-B
visible items: item1, item3

case3:
active filters: F1-1, F2-B, F3-X
visible items: no visible items

case4:
active filters: F1-1, F2-B, F2-C, F3-X
visible items: item4

**Comment by rob-kabob** [comment]
I've also been trying to this. Anyone have a solution??

**Comment by giotiskl** [comment]
Hello, to achieve this effect you can use the multiFiltering mode which can be achieved by using the .toggleFilter method of Filterizr

If you do .filterizr('toggleFilter', category1) and then  
 .filterizr('toggleFilter', category2) the desired effect will be achieved

**Comment by giotiskl** [comment]
@rob-kabob sorry for the late response, this is quite a peculiar use case and I'm afraid Filterizr doesn't support it. 

Essentially you wish to combine or and and multifiltering based on different layers of categories, but there is currently no support for such a use case.
