### ISSUE TITLE
Filter by two values at once

### ISSUE THREAD

**Issue by jordanneenan** [giotiskl/filterizr#117]
I have seen similar questions to this, but not this particular question - not sure if I'm missing something obvious.

I have a filter with 2 categories, each with a select field - let's say they're "Food" and "Colour". When I select a value from each field, let's say "Fruit" and "Red" and click the Apply button, I want the list to filter.

Right now my code will only work with one argument sent to it

`filterizd.filterizr('filter', $values);`

If $values is 'fruit', the filter works, but if $values is 'fruit, red' then nothing appears. Is it possible to get this working?

**Comment by jordanneenan** [comment]
If anyone from the future wanted to know how I fixed this, I switched to Isotope which does all of this and more out of the box.

**Comment by giotiskl** [comment]
To achieve what you were looking for is fairly straightforward, by checking the documentation.

Filterizr has a method called .toggleFilter which can be used to filter by having an arbitrary of categories active by default.
