### ISSUE TITLE
Has anyone got the filter list working in an html select list ?

### ISSUE THREAD

**Issue by arkid** [giotiskl/Filterizr#12]
My users filter list has grown to be very large (as its cms populated).  So I was thinking of replacing the list tags I have with a select field.   I've tried it and the plugin doesn't seem to work out of the box with this.  

So I want to confirm, is that correct and if so can I do anything to resolve?

**Comment by giotiskl** [comment]
Hello @arkid, yes this is very much possible but as there is no such preset control you'll have to set up a control of your own, using jQuery to check for example a custom data attribute on your select input, to see which category the user picked and then call Filterizr's public filter method like this ````fltr.filterizr('filter', categoryNumber);````

**Comment by giotiskl** [comment]
this is now also thoroughly answered by the answer at: https://github.com/giotiskl/Filterizr/issues/16
Thus, I'm closing this issue.

**Comment by arkid** [comment]
Thanks Yiotis!
