### ISSUE TITLE
[HELP] Adding items with Ajax

### ISSUE THREAD

**Issue by arianoangelo** [giotiskl/filterizr#126]
**Filterizr version**
2.2.3
**Describe the issue in details**
Hello, I'm doing a project where I need to add new items to my gallery with Filterizr. The project it's being done in WordPress, and I already made the AJAX call, but when I try to throw the data to "filterizr.insertItem(data)" It just throws me this error:

`vanilla.filterizr.min.js?ver=2.2.1:1 Uncaught (in promise) TypeError: t.cloneNode is not a function`

What am I doing wrong?

**Comment by giotiskl** [comment]
It looks like you're trying to pass directly the response of your AJAX request in the `insertItem` method.

`insertItem` expects an HTML element. Supposing you received an ajax response that looks kind of like:
````
{
    imgUrl: '...',
    description: '...',
}
````

You have to create an HTML element that will be an item in your grid like:
````
const item = document.createElement('img');
item.src = response.imgUrl;
filterizr.insertItem(item);
````

**Comment by arianoangelo** [comment]
And insertItem only expects ONE item with the same structure as the others, right?

**Comment by giotiskl** [comment]
@arianoangelo that's right

**Comment by arianoangelo** [comment]
Thank you!
