### ISSUE TITLE
[HELP] method 'includes' is not supported in IE11

### ISSUE THREAD

**Issue by bitseeker** [giotiskl/filterizr#128]
**Filterizr version**
2.2.3

**Describe the issue in details**
Still getting error in IE11, that the method 'includes' is not supported. I noticed the polyfill fix since ver. 1.3.5, but why still this error in IE 11?
Or did i miss something? 

IE11 doesn´t even open https://yiotis.net/filterizr/#/
-> 
SCRIPT438: Das Objekt unterstützt die Eigenschaft oder Methode "values" nicht
Datei: 2.1fe000f4.chunk.js, Zeile: 1, Spalte: 476798
<-

Any solution on this?

thx Olli

PS. using filterizr as jquery plugin (jquery ver 3.4.1)

**Comment by molnargabor** [comment]
I have the same problem.

**Comment by bitseeker** [comment]
@molnargabor: since not all features seem to be included in IE11, i´m loading the missing features through polyfill.io directly:
`<script crossorigin="anonymous" src="https://polyfill.io/v3/polyfill.min.js?features=default%2CArray.from%2CArray.prototype.entries%2CArray.prototype.values%2CObject.entries%2CObject.values%2CObject.assign%2CArray.prototype.includes%2CString.prototype.includes"></script>` 

you can also download the script and load it locally if you want.

That fixed the problem.

greets Olli

**Comment by molnargabor** [comment]
@bitseeker Thank you Olli! It works.
Br,
Gábor
