### ISSUE TITLE
Is it possible with infinite scroll function?

### ISSUE THREAD

**Issue by ceresyuyi** [giotiskl/Filterizr#13]
Description:
1. User can filter the items or scroll down the page.
2. If user filtered the items, while the page is scrolling down, new items attached to the page, and is filtered accordingly. The page will return some strings when data end.
3. User also can scroll down the page, then reach for the filters. Next, it will filter accordingly.

Current Situation:
1. I am using php to pull the data from mysql and display it on page. Pagination is used for view more data. 

How to do so easily? Use Ajax? I am newbie in JQuery.
So sorry if the question sounds dumb...

**Comment by giotiskl** [comment]
Hello @ceresyuyi,

this is currently something that will not be easily do-able but I'm looking into implementing functions to add and remove items dynamically to your Filterizr gallery in an upcoming patch.

**Comment by matmar-91** [comment]
When do you plan to add this feature?

**Comment by giotiskl** [comment]
@matmar-91 there's no concrete date yet but sometime during the summer, unfortunately I've got too much on my plate right now

**Comment by giotiskl** [comment]
This feature is now added in [1.3.0](https://github.com/giotiskl/Filterizr/releases/latest).

You simple need to call the method ```filterizr.filterizr('insertItem', $newItem);```, where the $newItem argument will be a jQuery node of your new item to add to the grid.
