### ISSUE TITLE
When using Filterizr on school courses sections, when we switch vrom « All items » to one section « …name… », the space under image is keeped.

### ISSUE THREAD

**Issue by Nemzag** [giotiskl/filterizr#130]
**Describe the bug**
In class, the professor wanted to use your library,
we are making a project,
with in home school courses sections,
when we switch vrom « All items » to one section « Names… »,
the space under image is keep‑ed.
I believe it's because you use `visibility:"hidden;"` instead of `display:"none;"`,
if you want to check by yourself here is the [project](https://github.com/Nemzag/2019-11-08_-_1362_-_Projet_Web_dynamique_-_learning-template).

**Filterizr version**
Which version of Filterizr do you have installed in your project?

**To Reproduce**
1. Go to 'All Courses' in nav‑bar.
2. Click on 'All Items', then an others,
3. Scroll down to 'The space is keeped' under "Restez en contact" and it's problematic.

**Expected behavior**
To not show that space,
use `display="none;"` instead of `visibility="hidden;"`.

Or may be you have a suggestion or commutator to use ?

**Screenshots**
https://mangzedi.files.wordpress.com/2019/11/annotation_2019-11-19_12h43m33s.png

https://mangzedi.files.wordpress.com/2019/11/annotation_2019-11-19_12h44m54s.png

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome & FireFox.

**Comment by giotiskl** [comment]
This issue is addressed in v2.2.4, please update to the latest version.
