### ISSUE TITLE
[HELP]How to use  two different filter image gallery in the same page.

### ISSUE THREAD

**Issue by Rony4927** [giotiskl/filterizr#136]
**Filterizr version**
Which version of Filterizr do you have installed in your project?
Answer: Latest version.

**Describe the issue in details**
I was added two different filter category.Some how its work.But show google console error.
```
jquery.filterizr.min.js:1 Uncaught TypeError: Cannot read property 'className' of undefined
    at k.fn.init.t.fn.filterizr (jquery.filterizr.min.js:1)
    at main.js:289
    at main.js:299
```

And I added this js code for my custom folder
```
  //gallery 1
  var filerizd = $('.methy').filterizr({
    setupControls: true,
    layout: 'sameSize',
    gridItemsSelector: '.filtr-item',
    gutterPixels: 30,
  });

  //gallery 2
  var filterSingle = $('.methy2').filterizr({
    setupControls: true,
    layout: 'horizontal',
    gridItemsSelector: '.filtr-item',
    gutterPixels: 30,
  });
```

**Comment by giotiskl** [comment]
@Rony4927 in order to have to galleries, I would propose using a different `gridItemsSelector` for each one of your galleries.

Also you should define a `controlsSelector` option with a different selector for the controls of each gallery.

**Comment by RabbiIslamRony** [comment]
Thank you so much.problem was solved
