### ISSUE TITLE
[HELP](question)

### ISSUE THREAD

**Issue by c0ncentus** [giotiskl/Filterizr#139]
**Filterizr version**
the latest

**Describe the issue in details**
I get the repo, I launch the demo as the same issue of https://github.com/giotiskl/filterizr/issues/138 did.

Why you can just <script src="cdnjs, or similar"></script>
and put the easiest code to test ? 

I got that from the demo 
![image](https://user-images.githubusercontent.com/25374826/83651112-6a596e00-a5b9-11ea-8281-755ee1204ea5.png)

i want to beleve on filterizr package because of ts power.
there is a way for old js world to get fast and build pretty things ?

it could be wonderfull and many people come to use this package 👍

**Comment by c0ncentus** [comment]
PS : ok I got it , i retrieve the file vanilla js, it worked 👍 but can you make <script> with cdnjs please ?

**Comment by giotiskl** [comment]
hello @c0ncentus, filterizr is already on CDN https://cdnjs.cloudflare.com/ajax/libs/filterizr/2.2.4/vanilla.filterizr.min.js (just google "cdn filterizr" and use the vanilla link)
