### ISSUE TITLE
filtering not working on list items with iOS

### ISSUE THREAD

**Issue by arkid** [giotiskl/Filterizr#14]
You can see my problem here: http://www.enhabit.uk.com/case-studies/ 

I've read list items sometimes don't capture click events in iOS and odd fixes like adding a cursor:pointer in CSS resolve it. No such luck here.

**Comment by giotiskl** [comment]
I am not sure I completely understand the nature of the problem, seems to work fine for me on Android. Unfortunately, I have no iOS to test it, but something that comes to mind is filtered out items being above visible items.
Try adding this rule to your CSS and see how it works out:
```
.filteredOut {
    z-index: -1;
}
````

**Comment by arkid** [comment]
Thanks for the idea... unfortunately no difference.

**Comment by giotiskl** [comment]
Was this error in Filterizr's code or in your codebase? If it was in Filterizr's code would you mind pointing out the error and the fix? Thanks.

**Comment by arkid** [comment]
Mine ;)
