### ISSUE TITLE
[HELP]

### ISSUE THREAD

**Issue by StifflersMom007** [giotiskl/Filterizr#146]
**Filterizr version**
Bootstrap Studio - Filtarable Cards
version 1.3.4

**Describe the issue in details**
on loading the site the filterizer loads all images. Is there a way to specify to load a data-category instead. 
The mission is not to show all awailable pictures on loading but only a specific category.
Can somebody help?
Regards
Paul

**Comment by giotiskl** [comment]
https://yiotis.net/filterizr/#/documentation/vanilla/options, using the `filter` option in the Filterizr options when creating your filterizr instance can load the grid with an initial filter applied
