### ISSUE TITLE
How can i work the filter by select option not a buttons 

### ISSUE THREAD

**Issue by MuhammadEid** [giotiskl/Filterizr#16]
Dear all how can i select the filter by select option not a buttons because i have more more items and i want to select filter by option 

thanks waiting your replay

**Comment by mmkaw** [comment]
you need to change 2 lines of code in the filterizr file. if owner @giotiskl  allows, i will post images to show the lines. its simple you need to implement "on change" event instead of "click event" and assign the value to targetFilter variable. its **working** but i have not tested thoroughly.

**Comment by MuhammadEid** [comment]
thanks so much i hope it will allow because i have project and need multi filter not single hope he will 

thanks so much again

**Comment by giotiskl** [comment]
@MuhammadEid actually this would be quite easy, you could just add a custom data-filter attribute to the <option> tags with the values set to the categories towards which you want to filter and then check in your script when the select changes the option and call the public filter method ````fltr.filterizr('filter', targetfilter);````
Otherwise, you can follow mmkaw's solution, which of course he can publish :) Filterizr is free and open in every aspect so please go again @mmkaw

**Comment by mmkaw** [comment]
![filterzr1](https://cloud.githubusercontent.com/assets/13604847/15270961/40f68424-1a50-11e6-8a6c-17e0de7a3978.jpeg)

**Comment by mmkaw** [comment]
![filterzr2](https://cloud.githubusercontent.com/assets/13604847/15270964/4a8d4a7c-1a50-11e6-9993-39164e9e4b98.jpeg)

**Comment by MuhammadEid** [comment]
Dear all i was change what need to do like steps you told me 

JS Code
 //Filter controls
            filteritems2.onchange = function() {
                var targetFilter = $('#filteritems2').val();
				$(this).addClass("active");
                //Exit case
                if (self.options.filter === targetFilter) return;
                self.filter(targetFilter);
            });

HTML Code
<div class="filteritems">
				<select id="filteritems2">
				  <option value="all">Volvo</option>
				  <option value="1">Saab</option>
				  <option value="2">Opel</option>
				  <option value="3">Audi</option>
				</select>
			</div>

any mistake thanks i'm waiting

**Comment by mmkaw** [comment]
is it not working?

**Comment by MuhammadEid** [comment]
Yes @mmkaw not working i was change everythink HTML and JS code

**Comment by giotiskl** [comment]
do you get any errors in your dev console @MuhammadEid ?

**Comment by MuhammadEid** [comment]
thanks @giotiskl  and @mmkaw  for every help that is my screens 

![111222333](https://cloud.githubusercontent.com/assets/17949963/15271055/dd84b636-1a36-11e6-84eb-94f4804a7fd5.png)
![Uploading 111222.png…]()
![Uploading 111.png…]()

**Comment by mmkaw** [comment]
whats the error message?

**Comment by MuhammadEid** [comment]
![111222](https://cloud.githubusercontent.com/assets/17949963/15271073/b1b751ca-1a37-11e6-8f1d-c070bcaf55ae.png)

**Comment by MuhammadEid** [comment]
![111](https://cloud.githubusercontent.com/assets/17949963/15271074/ba8f8a92-1a37-11e6-9e7a-768330cc745f.png)

**Comment by mmkaw** [comment]
remove bracket and semi coma ");" from line 466. its just close braces "}"

**Comment by mmkaw** [comment]
![filterzr1](https://cloud.githubusercontent.com/assets/13604847/15271083/b160c468-1a55-11e6-932b-36b1de1fb399.jpeg)

**Comment by MuhammadEid** [comment]
Yes It's Working thanks so so so much @mmkaw  and @giotiskl  for your support me it's working oooooooooooooo thankkkkks

**Comment by mmkaw** [comment]
welcome, thanks to owner for this plugin.

**Comment by giotiskl** [comment]
Good to see it is working :) Thanks for your help @mmkaw
