### ISSUE TITLE
Hover issue

### ISSUE THREAD

**Issue by sreekanthreddyk** [giotiskl/Filterizr#17]
i written a hover function i.e.. when a image hover i am displaying overlay with content. In this after filtering category wise on hover is coming very slow on first two images some times it is not coming. Is there any solution for this.

**Comment by giotiskl** [comment]
Are you sure don't have any filtered out items blocking your gallery?
Try adding this rule to your CSS
````
.filteredOut {
   z-index: -1;
}
````

**Comment by mmkaw** [comment]
its true, issue with z-index, but for some reason, adding z-index -1 to just filteredOut does not work, it will look like its working on dev console, need to add z-index 0 to filteredInCss too.
![f1](https://cloud.githubusercontent.com/assets/13604847/15329471/82654972-1c76-11e6-84ea-3017023702f8.jpeg)

**Comment by mmkaw** [comment]
is it working now @sreekanthreddyk ?

**Comment by giotiskl** [comment]
@mmkaw I was talking about actually adding it as a CSS rule in a CSS file since all filtered out items get a .filteredOut class ;)

**Comment by mmkaw** [comment]
tried adding .filteredOut { z-index: -1} in css file. but it doesn't work, and dev console does not show .filteredOut class nowwhere. ?

**Comment by giotiskl** [comment]
@mmkaw this feature was added in v1.1.0 ;) Are you sure you're not using an outdated version of Filterizr?

**Comment by mmkaw** [comment]
yep, using older version, sorry

**Comment by mmkaw** [comment]
issue solves by adding z-index : -1 to .filteredOut class in css file as @giotiskl said. tested on V 1.2.1
