### ISSUE TITLE
It  doesn't work on Wordpress.

### ISSUE THREAD

**Issue by jovicabojic** [giotiskl/Filterizr#19]
I kill myself :)!

**Comment by giotiskl** [comment]
@jovicabojic please do not do that for Filterizr :P Instead, share more details about the actual problem

**Comment by jovicabojic** [comment]
![screen shot 2016-05-17 at 19 10 44](https://cloud.githubusercontent.com/assets/15104810/15331765/249102fe-1c63-11e6-9f43-68800e483b1b.png)

**Comment by jovicabojic** [comment]
![screen shot 2016-05-17 at 19 24 51](https://cloud.githubusercontent.com/assets/15104810/15332250/281ea442-1c65-11e6-8c9f-9faf8090cf73.png)

**Comment by giotiskl** [comment]
Did you find the answer? @jovicabojic

**Comment by jovicabojic** [comment]
i did't find the answer, just started working.

**Comment by leecollings** [comment]
Please try to explain this, I'm getting the same.. in Wordpress. How can it just work?

**Comment by jovicabojic** [comment]
When i deactivated Sharebar plugin, it's simply started to work.
