### ISSUE TITLE
Inclusive/Excluse filtering mode

### ISSUE THREAD

**Issue by kazasoft** [giotiskl/Filterizr#20]
hello
I have a few data-multifilter
sample

```
<ul>
   <li data-multifilter="1"> Green </li>
   <li data-multifilter="2"> Orange </li>
   <li data-multifilter="3"> Purple </li>
</ul>
<ul>
   <li data-multifilter="4"> text1 </li>
   <li data-multifilter="5"> text2</li>
   <li data-multifilter="6"> text3</li>
</ul>

```

And i have some blocks

```
<div class="filtr-container">
    <div class="filtr-item" data-category="1,2,4" data-author="John Doe" data-year="1998" data-novel="Cool book 1">
       <img src="img/sample.jpg" alt="sample">
    </div>
    <div class="filtr-item" data-category="1,3,5" data-author="Jane Doe" data-year="2003" data-novel="Cooler book">
       <img src="img/sample.jpg" alt="sample">
    </div>
    <div class="filtr-item" data-category="4,6" data-author="Jake Doe" data-year="2008" data-novel="Coolest book">
       <img src="img/sample.jpg" alt="sample">
    </div>
</div>
```

in defaul mode if i choice category 1 and 4 Filtterzr result 1 OR 4.  But i need 1 AND 4. I need result only data-category="1,2,4" 

is there any option to set the sampling algorithm? some INCLUSIVE/EXCLISIVE mode... like this http://wch.io/projects/tagsort/demo-stacks/

**Comment by giotiskl** [comment]
Hello @kazasoft, if I understand you correctly you want to render items that would belong to both of these categories.

Currently, there is no such functionality supported but this is a nice idea for a future patch, so I will keep it in mind :+1:

**Comment by kazasoft** [comment]
Yes, you understand correctly.
I look forward to the introduction of the functional.

**Comment by frizbog** [comment]
+1 for this feature request.
Great widget!

**Comment by wihodges** [comment]
+1 
  
I tried doing some crazy stringing together of searchTerms but search bypasses the data-filter selections. Basically just becomes a search library...

**Comment by lbtuda** [comment]
+1 any news?

**Comment by xileftenurb** [comment]
+1 I need this to!

**Comment by matif78** [comment]
Hi Guy,

Can you please help me how to implement AND operator in the search.. :(

**Comment by xileftenurb** [comment]
if you check my pull request, it solve it (and add many other thing). check #61

**Comment by giotiskl** [comment]
This feature is now added in [1.3.0](https://github.com/giotiskl/Filterizr/releases/latest).

You simple need to set the option when instantiating ```$('.filtr-container').filterizr({ multifilterLogicalOperator: 'and' });```
