### ISSUE TITLE
Version problem

### ISSUE THREAD

**Issue by kennynaoh** [giotiskl/Filterizr#22]
Hello @giotiskl ,
I am the member of [cdnjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library.
But there is a question I want to ask.
I install the library on [npm](https://www.npmjs.com/package/filterizr) which is the 1.2.4 release version.
But the version in `/src/jquery.filterizr.js` shows 1.2.3.
Please help me confirm that.
Thanks for your help!

https://github.com/cdnjs/cdnjs/issues/7820

**Comment by giotiskl** [comment]
It is a typo mistake, I forgot to update the file

**Comment by kennynaoh** [comment]
Thanks!
