### ISSUE TITLE
Vanilla JS version?

### ISSUE THREAD

**Issue by thednp** [giotiskl/Filterizr#23]
I am looking for lighter alternatives for isotope.js and found this little thing. Now wondering if you plan on a plain Javascript version anytime soon.

I am also interested in teaming up and developing such a version.

**Comment by giotiskl** [comment]
hello @thednp unfortunately there are no such plans for the foreseeable future, perhaps down the road but Filterizr was developed to be a jQuery plugin

**Comment by thednp** [comment]
I know. However, the code is lightweight, very suitable for high performance apps. Also it's size makes it easy to do the transition. I will probably fork this later and will let you know about it.
