### ISSUE TITLE
Search and Filter doesn't work with dynamic loading in Safari/Chrome 

### ISSUE THREAD

**Issue by gyokuru** [giotiskl/filterizr#24]
Hello,

i've a html page which is loading dynamic content from a csv file:

> textToInsert[key]=<div class="col-xs-6 col-sm-6 col-md-4 col-lg-3 filtr-item"
> 
> data-category="'+obj['Criteria']+'" data-sort="'+obj['Surname']+' '+obj['Name']+'"><div class="card 
> 
> ...
> 
> $(textToInsert.join('')).appendTo('#teamMember');

and places this into 

> <div class="filtr-container">
> 
> <div id="teamMember"...

 The simplefilter, multifilter, and sortandshuffle works after this loading in Firefox4x and IE10, but doesn't work in Safari & Chrome.

I tried to update the CSS classes, hide/show the dom elements, to initialize the filtr-container with filterizr,... but nothing helps. What did i do wrong, is there something that i'm missing??

**Comment by giotiskl** [comment]
Try v2
