### ISSUE TITLE
landing page not loading correct

### ISSUE THREAD

**Issue by goransiriev** [giotiskl/Filterizr#25]
when i open my index.php i got this 

https://gyazo.com/c872caa8bcfd2bf92cf6b3773c6c7f12  // <-- Not correct 
https://gyazo.com/84b9bde721b7a9b14a91d5dc4d4e354a // <-- Correct
images not loading correct 
but when i click one menu Amatic or Netent its ok.... only on first loading i got this problem ... do you know how to fix this?

**Comment by giotiskl** [comment]
From Filterizr's website:

> If the height of your .filtr-item elements depends on images then you might have trouble, because their loading might be slow the height of your items might be messed up. To solve this issue you can either set the height of your images explicitly or perhaps make use of DeSandro's imagesLoaded script which is only 5kb!

Please never forget to go through the FAQ ;)

**Comment by goransiriev** [comment]
Thank you
i solved the problem 

`style="height: 171px;"`
