### ISSUE TITLE
Filterizr not working with hamburger menu

### ISSUE THREAD

**Issue by Arihska145** [giotiskl/Filterizr#27]
I've used Filterizr plug-in for my categories, but after creating a hamburger menu for my website, my categories stopped working. The screens bellow shows the error occurred.
Issue
![capture](https://cloud.githubusercontent.com/assets/20590600/17046493/d516087e-4f88-11e6-8420-d659d7a351bd.PNG)
Code
![capture2](https://cloud.githubusercontent.com/assets/20590600/17046492/d51413c0-4f88-11e6-9786-01a33683e0bd.PNG)

**Comment by giotiskl** [comment]
can you share your code? are you sure you've included filterizr.js before trying to initialize it in this inline script?

**Comment by Arihska145** [comment]
Here is the code. And yes, I've included filterizr.js before intializing it in the inline script
`<header>
    <a href="index.html" class="logo"><img src="img/logo1.png" id="logo" alt="logo"></a>
  <nav>
    <a href="#" class="hamburger">
      <div class="line"></div>
      <div class="line"></div>
      <div class="line"></div>
    </a>
    <ul class="clearfix menu">
      <li><a href="index.html">Home</a></li>
      <li><a href="about.html">About</a></li>
      <li><a class="active" href="portfolio.html">Portfolio</a></li>
    </ul>
  </nav>
</header>

        <div class="container">

        	<div class="row">

        		<div class="simplefilter">
                    <h1 class="title">My Work:</h1>
                    <h4 class="active" data-filter="all">All</h4>
                    <h4 data-filter="1">Video</h4>
                    <h4 data-filter="2">Animation</h4>
                    <h4 data-filter="3">Vector</h4>
                    <h4 class="tag" data-filter="4">Websites</h4>
                    <h4 data-filter="5">3D</h4>
                </div>
            </div>


            <div class="row">
                        
                <div class="filtr-container">
                    <div class="col-xs-6 col-sm-4 col-md-3 filtr-item" data-category="1" data-sort="A&R Bike Company">
                        <a href="a&rbike.html"><img class="img-responsive" src="img/bike.jpg" alt="bike"></a>
                        <span class="item-desc">A&R Bike Company</span>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-3 filtr-item" data-category="1" data-sort="A&R Happy Ferret">
                        <a href="a&rferret.html"><img class="img-responsive" src="img/ferret.jpg" alt="ferret"></a>
                        <span class="item-desc">A&R Happy Ferret</span>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-3 filtr-item" data-category="1" data-sort="Tween Video Shoot">
                        <a href="tweens.html"><img class="img-responsive" src="img/tweens.jpg" alt="tween"></a>
                        <span class="item-desc">Tween Video Shoot</span>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-3 filtr-item" data-category="1" data-sort="Sun Video Rotoscoping">
                        <a href="sun.html"><img class="img-responsive" src="img/sun.jpg" alt="sun"></a>
                        <span class="item-desc">Sun Video Rotoscoping</span>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-3 filtr-item" data-category="2" data-sort="From Russia To Canada">
                        <a href="fromrussiatocanada.html"><img class="img-responsive" src="img/From_Russia_to_Canada.jpg" alt="trip"></a>
                        <span class="item-desc">From Russia To Canada</span>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-3 filtr-item" data-category="2, 3" data-sort="Car">
                        <a href="car.html"><img class="img-responsive" src="img/car.jpg" alt="car"></a>
                        <span class="item-desc">Car</span>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-3 filtr-item" data-category="4" data-sort="Dancing Ballroom">
                        <a href="dancingballroom.html"><img class="img-responsive" src="img/Dancing_Ballroom.jpg" alt="dance"></a>
                        <span class="item-desc">Dancing Ballroom</span>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-3 filtr-item" data-category="4" data-sort="E-Lena">
                        <a href="e-lena.html"><img class="img-responsive" src="img/e-lena.jpg" alt="e-lena"></a>
                        <span class="item-desc">E-Lena</span>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-3 filtr-item" data-category="4" data-sort="Restless machines">
                        <a href="zera.html"><img class="img-responsive" src="img/ZERA.jpg" alt="zera"></a>
                        <span class="item-desc">ZERA Game Agency</span>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-3 filtr-item" data-category="4" data-sort="Twitch Tickets website">
                        <a href="twitchticket.html"><img class="img-responsive" src="img/Twitch_Ticket.jpg" alt="twitch"></a>
                        <span class="item-desc">Twitch Tickets website</span>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-3 filtr-item" data-category="4" data-sort="The World Of Cuisine website">
                        <a href="theworldofcuisine.html"><img class="img-responsive" src="img/restaurant.jpg" alt="cuisine"></a>
                        <span class="item-desc">The World Of Cuisine website</span>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-3 filtr-item" data-category="3" data-sort="Romeo & Juliet">
                        <a href="romeo&juliet.html"><img class="img-responsive" src="img/R&J.jpg" alt="r&j"></a>
                        <span class="item-desc">Romeo & Juliet</span>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-3 filtr-item" data-category="3" data-sort="Party Poster">
                        <a href="party.html"><img class="img-responsive" src="img/Party.jpg" alt="party"></a>
                        <span class="item-desc">Party Poster</span>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-3 filtr-item" data-category="3" data-sort="Kunzite-vector">
                        <a href="kun.html"><img class="img-responsive" src="img/Kun_ico.jpg" alt="kun"></a>
                        <span class="item-desc">Kunzite-vector</span>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-3 filtr-item" data-category="5" data-sort="Rail 3D">
                        <a href="rail.html"><img class="img-responsive" src="img/rail.jpg" alt="rail"></a>
                        <span class="item-desc">Rail 3D</span>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-3 filtr-item" data-category="5" data-sort="Ice-cream Box 3D">
                        <a href="ice-cream.html"><img class="img-responsive" src="img/Icberg_Icecream.jpg" alt="ice-cream"></a>
                        <span class="item-desc">Ice-cream Box 3D</span>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-3 filtr-item" data-category="3" data-sort="Pencil">
                        <a href="pencil.html"><img class="img-responsive" src="img/pencil.jpg" alt="pencil"></a>
                        <span class="item-desc">"Pencil" Drawing</span>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-3 filtr-item" data-category="3" data-sort="Old Picture Repair">
                        <a href="photo.html"><img class="img-responsive" src="img/Picture_repair.jpg" alt="repar"></a>
                        <span class="item-desc">Old Picture Repair</span>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-3 filtr-item" data-category="3" data-sort="Precice">
                        <a href="doctor.html"><img class="img-responsive" src="img/doctor_icon.jpg" alt="doctor"></a>
                        <span class="item-desc">Precice Mood Board</span>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-3 filtr-item" data-category="6" data-sort="More">
                        <img class="img-responsive" src="img/more.jpg" alt="more">
                        <span class="item-desc">More Comming</span>
                    </div>

                </div>
            </div>
        </div>

        
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
        <script src="js/jquery.filterizr.js"></script>
        <script src="js/controls.js"></script>
        <script src="js/vendor/jquery-1.11.2.min.js"></script>
        <script src="js/main.js"></script>

        
        <script type="text/javascript">
            $(function() {
                //Initialize filterizr with default options
                $('.filtr-container').filterizr();
            });
        </script>

**Comment by giotiskl** [comment]
you are including jquery twice in your project?
````
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="js/jquery.filterizr.js"></script>
<script src="js/controls.js"></script>
<script src="js/vendor/jquery-1.11.2.min.js"></script>
````

Please, try moving filterizr below jquery like this and see if the problem persists.
````
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="js/controls.js"></script>
<script src="js/vendor/jquery-1.11.2.min.js"></script>
<script src="js/jquery.filterizr.js"></script>
````

**Comment by Arihska145** [comment]
Thanks a lot, it solved my problem with categories and hamburger menu. Can you please also tell me what do I need to do to make my nav bar to fully stretch across the screen?
`  <header>
    <a href="index.html" class="logo"><img src="img/logo1.png" id="logo" alt="logo"></a>
  <nav>
    <a href="#" class="hamburger">
      <div class="line"></div>
      <div class="line"></div>
      <div class="line"></div>
    </a>
    <ul class="clearfix menu">
      <li><a href="contact.html">Contact</a></li>
      <li><a href="portfolio.html">Portfolio</a></li>
      <li><a class="active" href="about.html">About</a></li>
      <li><a href="index.html">Home</a></li>
    </ul>
  </nav>
</header>
<div>
<article>
	<div class="about">
		<h1 class="heading">Meet Arina</h1>
		<img src="img/doska.jpg" alt="doska" class="doska">
        <a href="https://www.facebook.com/Arina-Matveeva-607789469402199/" class="media"><img src="img/facebook.png" alt="facebook" class="media"></a>
        <a href="http://aryfairy.deviantart.com/" class="media2"><img src="img/deviantart.png" alt="deviantart" class="media2"></a>
	</div>
	</article>
</div>`

**Comment by giotiskl** [comment]
@Arihska145 I am glad your issue regarding Filterizr is solved and I am thus closing this issue. For any non-Filterizr related issues, please make use of the vast resources available on the web, Google is your best friend.
