### ISSUE TITLE
Init with sort order Desc

### ISSUE THREAD

**Issue by CharlyPoppins** [giotiskl/Filterizr#29]
Hi,

how can I init Filteriz with sort order desc ?

**Comment by kostasx** [comment]
You can use the `.filterizr('sort' [,attr] [,sortOrder])` syntax and use 'desc' as the `sortOrder` argument.
e.g. `.filterizr('sort', 'mySecondAttr', 'desc');`
See [the documentation page's](http://yiotis.net/filterizr/) **sort** method section for more details.

**Comment by CharlyPoppins** [comment]
Ok thx :)
