### ISSUE TITLE
Uncaught TypeError: $(...).filterizr is not a function

### ISSUE THREAD

**Issue by konskript** [giotiskl/Filterizr#30]
What is the problem of this? 

![filter1](https://cloud.githubusercontent.com/assets/20536714/17426321/18d38d58-5b09-11e6-920c-5535694dcb13.PNG)
![filter2](https://cloud.githubusercontent.com/assets/20536714/17426322/18d440d6-5b09-11e6-8974-b55ef9c4e618.PNG)

**Comment by giotiskl** [comment]
````
<script rel="stylesheet" type="text/css" ...>
````
looks to me you're instructing the browser to interpret filterizr.js as a stylesheet?
the ````<script>```` tag would work with an ````src```` attribute.. try:
````<script src="{{ base_url() }}/assets/js/filterizr.js"></script>````
