### ISSUE TITLE
cannot read property 'length' of underfine Filterizr.js:758

### ISSUE THREAD

**Issue by Yangsou** [giotiskl/Filterizr#35]
hi guy, I'm using Filterizr for my website and I have a bug when it's online.
pls tell me how can i fix it, thank you.
sorry my bad english.

**Comment by giotiskl** [comment]
Hello, can you provide your code?

**Comment by Triloworld** [comment]
Check class: add 'filtr-item' to child and 'filtr-container' to container because they are required. Check jQuery version. If you use jQuery 3.0 then use additional jQuery migrate.

**Comment by Farrukhzaman** [comment]
Hi Triloworld
I have add "filtr-container" and "filter-item" classes as you mentioned. But still i am getting same length error. Filter tabs not active when i click once but when i clicked 2nd time "Active" class appear.

**Comment by giotiskl** [comment]
This issue is most likely addressed by version [1.3.0](https://github.com/giotiskl/Filterizr/releases/latest).

If not, please reopen.
