### ISSUE TITLE
Multiple Filtizr on one page

### ISSUE THREAD

**Issue by Lobotomizer** [giotiskl/Filterizr#37]
Hey man,

thanks for your work! I'm really enjoying Filterizr on a current project of mine. There is just one point I can't cope with. I would like to set up two galleries on one page with default settings but for the moment the filter controls affect both galleries. I would like to control them separatly. This is a Jekyll project.

This is my two html gallery containers:
https://github.com/Lobotomizer/LS-Page/blob/master/1_artist.html

Here is the main sass file:
https://github.com/Lobotomizer/LS-Page/blob/Filterizr/css/main.scss

This is where I'm initiate Filterizr:
https://github.com/Lobotomizer/LS-Page/blob/Filterizr/js/filterizr-app.js

Here the javascript is called
https://github.com/Lobotomizer/LS-Page/blob/Filterizr/_includes/scripts.html

That should be the most important stuff. Thanks for your help in advance.

Hannes

**Comment by giotiskl** [comment]
Hello Hannes,

I am glad you're enjoying Filterizr. To set up two galleries on a single page, you need indeed to set up your own controls.

To do this you need to pass in the option to disable setting up default controls when instantiating your Filterizrs.

e.g.
````
var fltr = $('.filtr-container').filterizr({setupControls: false});
````

and then manually set up your controls calling Filterizr's methods from its public API depending on what you're trying to achieve.

e.g.

````
$('.show-all').click(function() {
  fltr.filterizr('filter', 'all');
});
````

**Comment by Lobotomizer** [comment]
Thanks a lot. With my own controls I could trigger both galleries.
