### ISSUE TITLE
How i can use Filterizr in Ajax loaded content?

### ISSUE THREAD

**Issue by mbdesign** [giotiskl/Filterizr#39]
I have some Categorie results load with Ajax and the Filterizr do not work.

array[0] is undefined  is the issue

How i can initailze Filterizr again?

And how it is possible to use in  data-category="1, 5"  words (string)  like   data-category="new wheel, other"

Also word with spaces must be possible

**Comment by mbdesign** [comment]
Hi, can somebody help?

**Comment by giotiskl** [comment]
These issues are now addressed in [1.3.0](https://github.com/giotiskl/Filterizr/releases/latest).

String categories now work by default.

To append new AJAX-loaded content you simple need to call the insertItem method like this ```filterizr.filterizr('insertItem', $node);``` where the $node is your new .filtr-item as a jQuery node.
