### ISSUE TITLE
lightbox, fancybox and other

### ISSUE THREAD

**Issue by nikol11** [giotiskl/Filterizr#42]
Hello. lightbox, fancybox and other fotos scripts show hidden fotos. I want it will be show only filtered fotos. How do it? Can you help me?
Sorry for my english...

**Comment by giotiskl** [comment]
This depends highly on the plugin being used together with Filterizr.

In Filterizr all filtered out images get a ```.filteredOut``` css class. Thus, you should take care to initialize your lightbox plugin with a set of images that do not have this class.
