### ISSUE TITLE
Clumping of items with Bootstrap 4

### ISSUE THREAD

**Issue by Jamal-Al-Hruti** [giotiskl/Filterizr#43]
[JS Fiddle](https://jsfiddle.net/qmLwLw61/12/)

In order to stay relevant Filterizr needs to work well with upcoming Bootstrap 4 - the dominating frontend framework.

Bootstrap 4 is major rework of framework. Much changing here.

Me tried to implement Filterizr in Bootstrap 4 alpha v6.

Unfortunately no longer working: **Items clump up** - forming irregular heaps, instead of evenly distributed grid. Filterizr does not position them correctly anymore.

This is issue with Filterizr + Bootstrap 4, as equivalent example works right in Bootstrap 3.

_Good to know: The clumped mess, can be made into intended grid structure on "shuffle"._

Yet: Just attaching shuffle at the end of filtering process no solution - as clumping still occurs, yet at lower frequency. It appears shuffle process sometimes not finishing. Shuffle callback not reached, see console log for missing "shuffling ended" message.

[JS Fiddle](https://jsfiddle.net/qmLwLw61/12/)

Instructions:

1. You may want to use different dimensions of HTML window.
2. Just hit the filter buttons several times to reproduce issue.
3. When clumped use shuffle to unclump to get and idea of what is meant.

NOTE: I changed line 85 of jquery.filterizr.js: self.slector -> self to make work good with jqery 3,
as suggested here: [other issue](https://github.com/giotiskl/Filterizr/issues/26)

**Comment by Jamal-Al-Hruti** [comment]
Update: After thorough testing I found the issue to be with jQuery version versus Bootstrap.
jquery 1 % 2 working fine, jquery 3 causing issue here.

This good to know: Best to explain dependencies on filterizr info page.

**Comment by martian-warlord** [comment]
Unfortunately, I'm in the same boat.  Filterizr is awesome and I would love to use it.  However, until it catches up with the latest JQuery/Bootstrap technologies I have to pursue other options.  Suggestions for alternatives would be appreciated.

**Comment by giotiskl** [comment]
@martian-warlord Filterizr now supports the latest jQuery versions
