### ISSUE TITLE
How to display a maximum of n filtr-items

### ISSUE THREAD

**Issue by bcccgreen** [giotiskl/Filterizr#44]
Hi there,

I only ever want to display for instance 6 filtr-items.

What is the best way to go about that?  The only thing I could come up with is try to hide them in one of the callbacks.

Regards,

Cameron

**Comment by bcccgreen** [comment]
For future reference, in set options this seemed to work.

 callbacks: {
            'onFilteringEnd': function () {
              $('div.filtr-container div.filtr-item').filter(function() {
                return $(this).css('opacity') !== '0';
              }).each(function(index) {
                if (index >= max_elements) {
                  $(this).css('opacity', '0');
                }
              });
            }
          }

**Comment by giotiskl** [comment]
@bcccgreen looks like a fine solution, thanks for sharing

**Comment by bcccgreen** [comment]
@giotiskl Actually in the end I did this with a pull request.  Seems to work well.
