### ISSUE TITLE
sorting of blocks not right using jquery 3.1.1 (blocks randomly get placed over each other when filtering)

### ISSUE THREAD

**Issue by r2get** [giotiskl/Filterizr#45]
Hi, first i want to say that i love this plugin. I tested it with jquey 3.1.1 and then sometimes when you filter the blocks dont look nice in a grid but the overlap eachother  see screenshots. but sometimes it looks "ok" again

but then when i use jquery1.12.0 (As in your demo) it works fine.

![screen shot 2017-02-20 at 23 00 21](https://cloud.githubusercontent.com/assets/3407104/23143275/d2128356-f7c0-11e6-9a15-65414892a9b9.png)
![screen shot 2017-02-20 at 23 00 13](https://cloud.githubusercontent.com/assets/3407104/23143279/d501a2b8-f7c0-11e6-833a-6423139e361b.png)

![screen shot 2017-02-20 at 23 00 32](https://cloud.githubusercontent.com/assets/3407104/23143270/cac8f6ca-f7c0-11e6-8797-25aad5774f50.png)

**Comment by govarthananve** [comment]
![capture](https://cloud.githubusercontent.com/assets/17062177/25674855/0b741458-305a-11e7-96f1-62c145cb907d.PNG)

when using jquery 3.1.1

**Comment by giotiskl** [comment]
@govarthananve @r2get the issue was being caused because Filterizr was lacking support for the latest versions of jQuery. As of today, the issue is addressed, just make sure to update to version 1.2.5.
