### ISSUE TITLE
Remove "All"

### ISSUE THREAD

**Issue by riyaadh47** [giotiskl/Filterizr#46]
Hi,

How can I start on data-filter="1" and remove data-filter="all" completely?

Thanks.

**Comment by giotiskl** [comment]
@riyaadh47 as dictacted by the docs (http://yiotis.net/filterizr/ -> DOCS), you must initialize Filterizr with the initial filter you want in the options.

So your initialization state will look like this: ````$('.filtr-container').filterizr({filter: 1})````
