### ISSUE TITLE
This happens on pages I do not use filterizr - $(...).filterizr is not a function

### ISSUE THREAD

**Issue by besnikh** [giotiskl/Filterizr#47]
Hi,
I just started to play around with filterizr and I am having a issue here and I am not sure why... 

On the page where I needed filterizr I do not get any error, but on other pages where I didn't even add the filterizr script tag I get the same error. 

```
Uncaught TypeError: $(...).filterizr is not a function
    at HTMLDocument.<anonymous> (app.js:11)
    at fire (jquery.js:3187)
    at Object.fireWith [as resolveWith] (jquery.js:3317)
    at Function.ready (jquery.js:3536)
    at HTMLDocument.completed (jquery.js:3552)
```

and my short app.js code looks like 

```
$(document).foundation()
$(document).ready(function() {
    $(".clc").click(function(){
         window.location=$(this).find("a").attr("href");
         return false;
    });
    $(".scs").click(function(){
         window.location=$(this).find("a").attr("href");
         return false;
    });
    $('.filtr-container').filterizr();
})
```

and the line 11 is $('.filtr-container').filterizr();

PS. 
#26 I followed this issue and changed the line as well... that didn't fix the issue here

Thank you in advance,

**Comment by giotiskl** [comment]
@besnikh my guess is that on the pages you do not use filterizr, you do not include the javascript file for it. Consequently, the filterizr method is not exported on the global jQuery object.

Wrapping your filterizr initialization line in the following code, should make the error go away
````
if ($('').filterizr) {
  $('.filtr-container').filterizr();
}
````

**Comment by besnikh** [comment]
@giotiskl Yeah that helped :+1: Thank you!
