### ISSUE TITLE
Blank Space on selecting any category except All

### ISSUE THREAD

**Issue by AsjadRex** [giotiskl/Filterizr#48]
This is the function that i am using to call filterizr.

function callFilter(){   
      if($('body.has-filterizr').length > 0){
        var filterizd = $('.filtr-container').filterizr({
          delay: 25,
          delayMode: 'progressive',
          layout: 'sameWidth'
        });
      }
}

Issue i am facing is blank space that shows on the bottom as soon i filter using any category other than All.

Can you guide what might be causing this behavior?

![capture](https://cloud.githubusercontent.com/assets/25365206/23902192/13edf0f8-08e2-11e7-99c9-39a4ae4b4bee.PNG)

**Comment by lrtr** [comment]
Hi, I am having this problem as well. I don't have a clue what is causing it.
This behaviour is really frustrating and I hope you will find time to look at this issue.

**Comment by lrtr** [comment]
I found a workaround.
I modified the script by adding display: none/block to the added properties when the filter is executed. The animation is gone but it's better than having blank space at the end of the page.

**Comment by giotiskl** [comment]
this is not an issue of Filterizr. It is caused by the fact that the height of the `document` is less than the height of the `window`.

You need to google and apply a sticky footer solution for your website.

**Comment by AsjadRex** [comment]
@giotiskl  Thanks. I will bear that in mind for future. That project was done long ago.

**Comment by wilbertcaba** [comment]
@AsjadRex I found that applying `overflow: hidden` to the parent that contains the Filterizr grid fixed the same problem for a project I was working on.
