### ISSUE TITLE
Filterizr image height not working with lazyLoading 

### ISSUE THREAD

**Issue by Nsokyi** [giotiskl/filterizr#53]
Hi,

I know in the FAQ section you talk about images not being the right height because they are loaded in the DOM after the plugin has been initialised. So I'm trying it with imagesLoaded with the following: 

`jQuery('.filtr-container').imagesLoaded(function() {

            var filterizd = jQuery('.filtr-container').filterizr({
                animationDuration: 0.5, //in seconds
                delay: 150,
                delayMode: 'progressive',
                easing: 'ease-out',
                filter: 'all',
                filterOutCss: { //Filtering out animation
                          
                    opacity: 0,
                    transform: 'scale(0.5)'   
                },
                   filterInCss: { //Filtering in animation
                          
                    opacity: 1,
                    transform: 'scale(1)'   
                },
               layout: 'sameSize',
               selector: '.filtr-container',
               setupControls: true
            });
        });`

HTML

`<div class="portfolio">
          <div class="filtr-container">

            <div class="filtr-item project-item " data-category="1" data-sort="hello">
              <figure class="fancy-effect">
                <picture>
                  <source data-srcset="/assets/img/hello-small.jpg" media="(max-width: 425px)" />
                  <source data-srcset="/assets/img/hello-medium.jpg" media="(min-width: 1024px)" />
                  <source data-srcset="/assets/img/hello-large.jpg" media="(max-width: 1440px)" />
                  <img data-src="/assets/img/webdesign/hello-medium.jpg" alt="hello screenshot" class="lazyload">
                </picture>
                <figcaption>
                  <h2 class="project-title">Hello</h2>
                  <p class="project-subtitle"></p>
                  <p class="project-tech">Wordpress, HTML5, CSS3, SCSS, jQuery</p>
                  <a class="project-link" href="#project-item01">View Slides</a>
                </figcaption>
              </figure>
            </div>

          </div>
        </div>`

CSS: 

     ` .portfolio,
        .filtr-container {
            display: block;
            position: relative
        }

        .filtr-container {
            margin: 0 auto;
            padding: 1em 0 4em;
            text-align: center;
            float: left;
            display: block;
            margin-right: 13.30108%;
            width: 100%
        }

        .filtr-container {
            float: left;
            display: block;
            margin-right: 8.49092%;
            width: 100%
        }

        .filtr-container .project-item {
            display: block;
            position: relative;
            float: left;
            float: left;
            display: block;
            margin-right: 13.30108%;
            width: 100%
        }

        .project-item figure {
            display: block;
            background: #383838;
            cursor: pointer;
            float: left;
            margin: 15px 1%;
            overflow: hidden;
            position: relative;
            text-align: center;
            width: 100%
        }

        .project-item figure img {
            display: block;
            height: auto;
            max-width: 100%;
            min-height: 100%;
            opacity: 0.8;
            position: relative
        }

        .project-item figure>figcaption {
            -o-backface-visibility: hidden;
            backface-visibility: hidden;
            color: white;
            font-size: 1em;
            height: 100%;
            left: 0;
            padding: 1em;
            position: absolute;
            text-transform: uppercase;
            top: 0;
            width: 100%;
            float: left
        }

        .project-item figure>figcaption::after,
        .project-item figure>figcaption::before {
            pointer-events: none
        }

        .project-item figure>figcaption>a {
            overflow: hidden;
            text-indent: 101%;
            white-space: nowrap;
            opacity: 0;
            z-index: 1000
        }

        .project-item figure>figcaption h2.project-title,
        .project-item figure>figcaption p {
            margin: 0
        }

        figure.fancy-effect {
            background: #D8D8D8
        }

        figure.fancy-effect img {
            max-width: none;
            width: -o-calc(100% + 10px);
            width: calc(100% + 10px);
            -o-transition: opacity 0.35s, -o-transform .35s;
            -o-transition: opacity 0.35s, -o-transform .35s;
            transition: opacity 0.35s, transform .35s;
            -o-transform: translate3d(-10px, 0, 0);
            -o-transform: translate3d(-10px, 0, 0);
            -ms-transform: translate3d(-10px, 0, 0);
            -o-transform: translate3d(-10px, 0, 0);
            transform: translate3d(-10px, 0, 0);
            -o-backface-visibility: hidden;
            backface-visibility: hidden
        }

        figure.fancy-effect:hover img {
            opacity: 0.099;
            -o-transform: translate3d(0, 0, 0);
            -o-transform: translate3d(0, 0, 0);
            -ms-transform: translate3d(0, 0, 0);
            -o-transform: translate3d(0, 0, 0);
            transform: translate3d(0, 0, 0)
        }

        figure.fancy-effect figcaption {
            text-align: left
        }

        figure.fancy-effect h2 {
            position: relative;
            overflow: hidden;
            padding: .5em 0
        }

        figure.fancy-effect h2::after {
            background: #383838;
            bottom: 0;
            content: '';
            height: 3px;
            left: 0;
            position: absolute;
            width: 100%;
            -o-transition: -o-transform .35s;
            -o-transition: -o-transform .35s;
            transition: transform .35s;
            -o-transform: translate3d(-100%, 0, 0);
            -o-transform: translate3d(-100%, 0, 0);
            -ms-transform: translate3d(-100%, 0, 0);
            -o-transform: translate3d(-100%, 0, 0);
            transform: translate3d(-100%, 0, 0)
        }

        figure.fancy-effect:hover h2::after {
            -o-transform: translate3d(0, 0, 0);
            -o-transform: translate3d(0, 0, 0);
            -ms-transform: translate3d(0, 0, 0);
            -o-transform: translate3d(0, 0, 0);
            transform: translate3d(0, 0, 0)
        }

        figure.fancy-effect p {
            opacity: 0;
            padding: .3em 0;
            word-spacing: 216px;
            -o-transition: opacity 0.35s, -o-transform .35s;
            -o-transition: opacity 0.35s, -o-transform .35s;
            transition: opacity 0.35s, transform .35s;
            -o-transform: translate3d(-10px, 0, 0);
            -o-transform: translate3d(-10px, 0, 0);
            -ms-transform: translate3d(-10px, 0, 0);
            -o-transform: translate3d(-10px, 0, 0);
            transform: translate3d(-10px, 0, 0)
        }

        figure.fancy-effect:hover p {
            opacity: 1;
            -o-transform: translate3d(0, 0, 0);
            -o-transform: translate3d(0, 0, 0);
            -ms-transform: translate3d(0, 0, 0);
            -o-transform: translate3d(0, 0, 0);
            transform: translate3d(0, 0, 0)
        }`

Seemingly both 'filtr-container ' and 'filtr-item' laod with the wrong height. I have tried messing around with `.lazyload` class with some successes but it requires adding loads of media queries to the height at different browser window widths. 

I have been trying things for few days now and I'm just wondering if there is a neat way to either get  imagesLoaded to work or if I can add a flexible height to the `.lazyload`/`.lazyloaded` class? i.e. 

        `.project-item {
        	figure {
        		display: block;
            background: $light;
            cursor: pointer;
            float: left;
            margin: 10px 1%;
            overflow: hidden;
        		position: relative;
            text-align: center;
        		width: 100%;

        		img {
        			display: block;
        			height: auto;
        			max-width: 100%;
        			min-height: 100%;
        			opacity: .8;
        			position: relative;

        		          &.lazyload,
        		          &.lazyloaded {
        			     'style that would give me the same height as img/figure no matter the browser width?'
        			}
        		}`

Thanks

**Comment by cokll** [comment]
filterizd.filterizr('setOptions', {
  setupControls: false
})

**Comment by giotiskl** [comment]
if you have lazily loaded images you can now add them to grid using the `insertItem` method. Since v2.1.0 Filterizr will take care automatically of the size of the image, since now imagesLoaded is baked into Filterizr
