### ISSUE TITLE
Fix line 948 please - remove space after comma in split function

### ISSUE THREAD

**Issue by RWSDev** [giotiskl/Filterizr#55]
current line 948: 
`ret = ret.split(', ');`
should be:
`ret = ret.split(',');`

Thanks, spent about 1 hour trying to figure out why my array to string wasn't working in filter when it turned out to be a f**king space that should not be there.  There is no reason to include the space on the split, this is just plain old BAD coding practice.

**Comment by giotiskl** [comment]
This issue is now addressed in [1.3.0](https://github.com/giotiskl/Filterizr/releases/latest).
Version 1.3.0 is a major rewrite of the core in ES6 and modern best practices.
