### ISSUE TITLE
filtr-item images periodically clumping/stacking upon page load

### ISSUE THREAD

**Issue by bmikol** [giotiskl/Filterizr#59]
This may be related to [Issue 43](https://github.com/giotiskl/Filterizr/issues/43), but I implemented Filterizr into a portfolio template and periodically the images will appear stacked in a (orderly) staggered fashion upon page load. It happens maybe 1-3 times out of 10 on my local machine and maybe 7-9 times/10 on a Heroku dyno. I've tried switching jquery from a CDN link to a local copy under the suspicion it might be due to a difference in loading lag, but that appears to have no effect. I've also updated Filterizr to 1.2.5 also to no effect.

I tried backing the `.filtr-item` class out of the HTML to see on the off-chance maybe the template was the problem, but given that refreshing the page 20-30 times didn't yield this problem once it leads me to conclude this issue is with Filterizr.

**Affected Version(s):** 1.2.3 and 1.2.5
**jQuery Version:** 2.2.4

**Comment by giotiskl** [comment]
This is not a bug. There is a thorough explanation as to why it might happen on Filterizr's website http://yiotis.net/filterizr -> Faq & Caveats ->Why my images appear without height.

**Comment by bmikol** [comment]
Ah! I missed that! Yup, using imagesLoaded.js fixed it - sorry about blowing by that FAQ! (And thanks!)
