### ISSUE TITLE
ability to use String categories instead of numbers

### ISSUE THREAD

**Issue by hoomb** [giotiskl/Filterizr#6]
it would be great if you could add support String categories. One option would be using multiple CSS selectors which can be combined to have logical operations and also very flexible filter definition:

```
<li class="btn-primary filtr-button filtr" data-filter=".cat-1.cat-2"> AND FILTER </li>

<li class="btn-primary filtr-button filtr" data-filter=".cat-1, .cat-2"> OR FILTER </li>

```

Thank you.

**Comment by darcome** [comment]
Yes, I'd really appreciate it, because it would allow me to put ids of my objects as categories... for example, I have "region" and "tipology" filters... but both have an id of 1. With a string category I coould use r1 and t1 as filter. As of now, I'd have to add a global id to represent different things...

Thanks in advance for your help

**Comment by giotiskl** [comment]
Using CSS selectors as possible values for the data-filter attribute in button controls sounds interesting indeed, I'll be looking into it in the future.

**Comment by arkid** [comment]
+1

**Comment by owldesign** [comment]
+1

**Comment by hoomb** [comment]
Please close my reported issue as it is not a case for me anymore. I have switched to Isotope (http://isotope.metafizzy.co/) which has the exact functionality that I need and offers an interface for real applications. The Idea with using numbers as categories may work for a little test application but not really transferable to a real application. Thank you.

**Comment by giotiskl** [comment]
you're welcome hoomb, isotope is indeed an amazing plugin with a great community and very battle tested but I need not close this issue right now as this is a feature very much wanted and I will be adding it to Filterizr in the future.

**Comment by math-u** [comment]
+1

**Comment by giotiskl** [comment]
This feature is now added in [1.3.0](https://github.com/giotiskl/Filterizr/releases/latest).
