### ISSUE TITLE
Can I use more than one set of data-filter in one filter?

### ISSUE THREAD

**Issue by ckkkeanu** [giotiskl/Filterizr#60]
For example,

filter 1: A B C
filter 2: 1 2 3

A1 A2 A3 B1 B2 B3 C1 C2 C3

I want to apply both filter 1 and 2 but only can choose one in each filter.

How can I apply this??? Thanks so much
```

<div class="row">
            <ul class="simplefilter">
                Simple filter controls:
                <li class="active" data-filter="all">All</li>
                <li data-filter="1">Cityscape</li>
                <li data-filter="2">Landscape</li>
                <li data-filter="3">Industrial</li>
                <li data-filter="4">Daylight</li>
                <li data-filter="5">Nightscape</li>
            </ul>
        </div>
<div class="row">
            <ul class="simplefilter">
                Simple filter controls:
                <li class="active" data-filter="all">All</li>
                <li data-filter="1">Cityscape</li>
                <li data-filter="2">Landscape</li>
                <li data-filter="3">Industrial</li>
                <li data-filter="4">Daylight</li>
                <li data-filter="5">Nightscape</li>
            </ul>
        </div>

```

**Comment by xileftenurb** [comment]
Hi,

check my brand new pull request (#61). maybe it will help you with this?
if not, I think it could be a good starting point to add the exact feature you need.

do you want the filter to perform a logical OR or a logical AND between your to filter?
(if I choose "A" and "1", do I got "A1", or "A1, A2, A4, B1, C1"?)

**Comment by giotiskl** [comment]
This feature is now added in [1.3.0](https://github.com/giotiskl/Filterizr/releases/latest).

You simple need to set the option when instantiating ```$('.filtr-container').filterizr({ multifilterLogicalOperator: 'and' });```
