### ISSUE TITLE
Pre-question

### ISSUE THREAD

**Issue by bhuisman1992** [giotiskl/Filterizr#62]
Hi there,

I am asking this question to see if the following is possible:

For example:
Each item has multiple categories.. maybe like this:

Item 1 has:
Category 1:  Living room
Category 2: Modern style
Category 3: The color blue

Item 2 has:
Category 1: Garden
Category 2: Modern style
Category 3: The color green

Is it possible to have 3 filters (for each category)? So if some one selects Living room + modern style they only get item 1 as the result? 

Hope you get what i am trying to achieve... Many thanks in advance

**Comment by xileftenurb** [comment]
my (pending) pull request (#61 ) add this feature.
without it, not, it is not feasible at the moment.

**Comment by giotiskl** [comment]
Thia feature is now added in v 1.3.0, check #68
