### ISSUE TITLE
How can i 'destroy' plugin on resize ? 

### ISSUE THREAD

**Issue by Koniksan** [giotiskl/Filterizr#63]
I need initialize plugin when window width more than 1024px and uninit when width is less than 1024px. 
Can i do this with default plugin options ?

**Comment by ogonkov** [comment]
Seems there is no way to destroy plugin

**Comment by giotiskl** [comment]
There is no method in the API for this. 

Right now Filterizr's core code is being rewritten to conform with ES6, best practices and will be more modular, sturdier and more well-tested, with many new features.

If you need a temporary solution until then, provided you have your filterizr's instance, if you initialized like ```` var filterizr = $('.filter-container').filterizr()```` then you could write a function that looks sth like this:
````
function destroyFilterizr(filterizrInstance) {
  filterizrInstance.attr('style', '');
  filterizrInstance.find('.filtr-item').attr('style', '');
  filterizrInstance._fltr = undefined;
  $(window).off('resize');
}

destroyFilterizr(filterizr);
````

**Comment by ogonkov** [comment]
> $(window).off('resize');

... and broke all logic of your code

**Comment by giotiskl** [comment]
@ogonkov he can reattach handlers, no matter how expensive it might be. 
This was meant as a hacky quickfix until the upcoming version is available.
Another alternative would be to use some of the other plugins similar to Filterizr that are available, the current version has **no** efficient way of doing this.

**Comment by Koniksan** [comment]
@giotiskl I done in one way solution , init filter when window gets  > requiredWidth , if width is decrease , we need to reload the page.
Any way thanks for the answer , good plugin by the way, i will reuse it on another project :)

**Comment by giotiskl** [comment]
@Koniksan glad you enjoy Koniksan, soon there will be a much sturdier and feature-full version coming. Feel free to star the repo if you haven't already to watch out for the update :)
