### ISSUE TITLE
Refresh the filtr-item position

### ISSUE THREAD

**Issue by shaasa** [giotiskl/Filterizr#64]
Hi,
in my page I use filteriz on items that can change heigth (users can drag and drop some other element into the filtr-item than change the height). Is there the way to refresh the item position in some way ?

Thank you,
Beatrice

**Comment by giotiskl** [comment]
Hello @shaasa,
you would have to retrigger the filter method programmatically passing the active filter to trigger a repositioning.

**Comment by shaasa** [comment]
works! Thank you

**Comment by gkrinc** [comment]
I'm also facing this dilemma. Which filter method should be called here? `filter` or `toggleFilter`? Would it not be easier to just supply a `redraw` method?
