### ISSUE TITLE
How do i get first category as initial display instead of all

### ISSUE THREAD

**Issue by vivinblue** [giotiskl/Filterizr#65]
I like this awesome plugin. It's easy to use and implement, Everything is fine but I want my first category to display on initial page load instead of getting all element (grid). Is it possible?

**Comment by giotiskl** [comment]
Hello, please consult the documentation for similar issues.

To do this you simply need to set the filter option when instantiating Filterizr like this:
````
$('.filtr-container').filterizr({ filter: 1 })
````
where 1 is your categoy name to be used as initial filter.
