### ISSUE TITLE
Category filter with no items produces an error when clicked

### ISSUE THREAD

**Issue by lewebsimple** [giotiskl/Filterizr#66]
Are empty categories supported in Filterizr?

Clicking on a category filter with no matching items in the container produces an error in the console (i[0] is undefined in _calcItemPositions jquery.filterizr.js:563). The other filters work perfectly.

**Comment by giotiskl** [comment]
This is now addressed [1.3.0](https://github.com/giotiskl/Filterizr/releases/latest). Empty categories are supported.
