### ISSUE TITLE
Filter for not displaying items ?

### ISSUE THREAD

**Issue by Deedidi27** [giotiskl/Filterizr#67]
Hello, 
Thank you. This is great. 
I'd like to know if it's possible to click on a filter button to not displaying any items.
Knowing that we can put for example data-filter="all" ... I'd like something to be data-filter="none" for example.

Thanks again !

**Comment by giotiskl** [comment]
@Deedidi27 [1.3.0](https://github.com/giotiskl/Filterizr/releases/latest) now supports empty categories.

i.e. you could have a button like that ```<button ... data-filter="none">...</button>```. Provided none of your items have the category "none" then an empty grid will be rendered.
