### ISSUE TITLE
Filter with AND operator rather then OR

### ISSUE THREAD

**Issue by matif78** [giotiskl/Filterizr#68]
Hi,
Can you please help me how can i manage filtration with AND operator ?

Thanks
Atif

**Comment by kazasoft** [comment]
look at my code... sorry I dont remember how I do this
http://tatd.ru/pod

**Comment by matif78** [comment]
Thanks Kazsoft,

did you update jquery.filterizr.min.js ? 

Thanks

**Comment by kazasoft** [comment]
No
i include
    <script src="/media/filterizr/jquery.filterizr.js"></script>
    <script src="/media/filterizr/controls.js"></script>
i am lazy

**Comment by matif78** [comment]
Cheer Thanks mate... :) it working

**Comment by giotiskl** [comment]
This feature is now added in [1.3.0](https://github.com/giotiskl/Filterizr/releases/latest).

You simple need to set the option when instantiating ```$('.filtr-container').filterizr({ multifilterLogicalOperator: 'and' });```
