### ISSUE TITLE
this feature make it possible to have AND logical operation with filter.

### ISSUE THREAD

**Issue by matif78** [giotiskl/Filterizr#69]
Hi,
I have updated jquery.filterizr.min and also put data-groupmultifilter but still showing error 

Uncaught TypeError: Object.Assign is not a function
    at n.fn.init.toggleFilter (jquery.filterizr.min.js:1)
    at HTMLInputElement.<anonymous> (jquery.filterizr.min.js:1)
    at HTMLInputElement.dispatch (jquery.min.js:3)
    at HTMLInputElement.r.handle (jquery.min.js:3)

Can you please tell me how to fix this?

Thanks
![capture_error](https://user-images.githubusercontent.com/27421700/31014276-e1ffcc7a-a511-11e7-909f-0f6f53199542.PNG)

**Comment by giotiskl** [comment]
This feature is now added in [1.3.0](https://github.com/giotiskl/Filterizr/releases/latest).

You simple need to set the option when instantiating ```$('.filtr-container').filterizr({ multifilterLogicalOperator: 'and' });```
