### ISSUE TITLE
is it posible to integrate it within vuejs?

### ISSUE THREAD

**Issue by almeidatercero** [giotiskl/filterizr#71]
im making a catalogue with this awesome plugin but i need to now how to use it w vue js and make it Ajax calls, right now i can make it work but outside vue js if anyone knows how, will be appreciate it

**Comment by giotiskl** [comment]
Hello, v2 has turned Filterizr into a vanilla Javascript library. It should be fairly straightforward to integrate with Vue, but you will have to investigate. React support coming soon in form of library
