### ISSUE TITLE
Issue with transforms, placement and width/height calculations (when using jQuery version less than 3.2.0)

### ISSUE THREAD

**Issue by tmoffett-centrify** [giotiskl/filterizr#72]
@giotiskl 
This isn't really an issue with your library, but you should recommend using jQuery 3.2.0 or later with your library [https://blog.jquery.com/2017/03/16/jquery-3-2-0-is-out/](https://blog.jquery.com/2017/03/16/jquery-3-2-0-is-out/).  If you already mention it somewhere, I apologize, but I don't recall seeing it specifically mentioned anywhere.  At the very least, I would hope this would help anyone else encountering this issue.

Before using your library, I wasn't aware that jQuery had an issue with calculating width and height on transformed elements. I just never ran into a case like this until I was using your library.  It was causing all sorts of messes with calculating the positions and sizes of the filtered items, which I at first thought was a bug with your library or some CSS from my site that is applied on the elements I am filtering, which was messing with the library.  I saw that all the demos on your site worked though, so I had to do some digging, and then I finally realized my jQuery version was different than yours.

**Comment by danverde** [comment]
+1

**Comment by giotiskl** [comment]
v2 drops dependency on jquery altogether. Issue should be resolved
