### ISSUE TITLE
Filter menu for desktop and select menu for mobile

### ISSUE THREAD

**Issue by webdev2178** [giotiskl/Filterizr#74]
Would it be possible to use the filter menu (list items) as coded and add a drop down/select menu for smaller screens?  I was planning on changing visibility of div depending on screen size:

`<div id="filter-list" class="row">
<ul class="simplefilter">
 	<li class="all" data-filter="all">View All</li>
 	<li class="option1" data-filter="1">Option 1</li>
 	<li class="option2" data-filter="2">Option 2</li>
 	<li class="option3" data-filter="3">Option 3</li>
 	<li class="option4" data-filter="4">Option 4</li>
</ul>
</div>
<div id="filter-select"><select>
<option value="all" data-filter="1">View All</option>
<option value="option1" data-filter="2">Option 1</option>
<option value="option2" data-filter="3">Option 2</option>
<option value="option3" data-filter="4">Option 3</option>
<option value="option4" data-filter="5">Option 4</option>
</select>
</div>`

thank you!

**Comment by webdev2178** [comment]
Here is solution:
Line 459 - add code for select ID "filteritems2"
`
//Filter controls
            $('*[data-filter]').click(function() {
                var targetFilter = $(this).data('filter');
                //Exit case
                if (self.options.filter === targetFilter) return;
                self.filter(targetFilter);
            });
            
            filteritems2.onchange = function() {
                var targetFilter = $('#filteritems2').val();
                $(this).addClass("active");
                //Exit case
                if (self.options.filter === targetFilter) return;
                self.filter(targetFilter);
            };
`
HTML:
`
<div id="filter-list" class="row">
<ul class="simplefilter">
 	<li data-filter="all">All Assets</li>
 	<li data-filter="1">Asset 1</li>
 	<li data-filter="2">Asset 2</li>
 	<li data-filter="3">Asset 3</li>
 	<li data-filter="4">Asset 4</li>
 	<li data-filter="5">Asset 5</li>
 	<li data-filter="6">Asset 6</li>
</ul>
</div>
<div id="filter-select" class="simplefilter"><select id="filteritems2">
<option value="all">View All Assets</option>
<option value="1">Asset 1</option>
<option value="2">Asset 2</option>
<option value="3">Asset 3</option>
<option value="4">Asset 4</option>
<option value="5">Asset 5</option>
<option value="6">Asset 6</option>
</select></div>
`
CSS:
` 
#filter-list{ visibility: visible; }
#filter-select{ visibility: hidden; }
`

**Comment by giotiskl** [comment]
issue considered resolved.
