### ISSUE TITLE
Container height not working

### ISSUE THREAD

**Issue by carlosromanxyz** [giotiskl/Filterizr#75]
Hi

I've a container with images and text inside, the images have the same height and width, but when loading the main container takes a very small height at random times. 120 pixels at least

And the main container has a 1264 pixels, i don't understand how to use imagesLoaded library

Currently i'm solving with fixed height in CSS:

`#home-projects .filtr-item {
    height: 316px;
}`

**Comment by giotiskl** [comment]
Using imagesLoaded is quite simple. Your JS snippet that instantiates Filterizr should be like that:

```
$('.filtr-container').imagesLoaded( function() {
  // images have already loaded, instantiate Filterizr
  var filterizr = $('.filtr-container').filterizr();
});
```
