### ISSUE TITLE
Cant initialize filterizr in elements with more than one class

### ISSUE THREAD

**Issue by Lydnasty** [giotiskl/Filterizr#77]
Version: 1.3.0

Error: Filterizr: could not find a container with the selector .grid row small-up-2 medium-up-3, to initialize Filterizr.

HTML:
`<div class="grid row small-up-2 medium-up-3">...`

Javascript:
`$('.grid').filterizr({...`

This used to work. Something has been broken in the last update...

**Comment by Lydnasty** [comment]
I can confirm it works in 1.2.5

**Comment by giotiskl** [comment]
@Lydnasty thanks for the bug report just published [1.3.1](https://github.com/giotiskl/Filterizr/releases/tag/1.3.1) with a hotfix to this
