### ISSUE TITLE
Do we have other options for this!!

### ISSUE THREAD

**Issue by rajkvx** [giotiskl/Filterizr#8]
3 Data Filter Menu Items so it gives 3 content blocks!!

1st Menu item - I used 3 items per row, total 3 rows (1st content block) (item width 300px)
2nd Menu item - I used 1 item per row (2nd block)  (item width 780px) (Which is not happening, in that 2nd item is running away out of window)

problem is, i want 3 items per row in scene 1, and 1 item per row in scene 2!!  Attached the shots
![shot-1](https://cloud.githubusercontent.com/assets/18647525/14770278/1aeb9136-0a8b-11e6-803a-bb16540c85a0.png)
![shot-2](https://cloud.githubusercontent.com/assets/18647525/14770287/52830408-0a8b-11e6-95e8-a9a1ecfe18d6.png)

is it layout: 'sameSize', related???

**Comment by giotiskl** [comment]
As you guessed it this has to do with the layout. Filterizr by default uses the layout 'sameSize' for items of same width and height. In your case you could use either layout 'sameHeight' (if only the width varies and the height is the same) or layout 'packed' if both the width and height varies between items.
You can find more information on such issues as well as numerous tutorial on a number of issues on Filterizr's website:
http://yiotis.net/filterizr

**Comment by rajkvx** [comment]
You mentioned it right!!  Thanks

I am on site.
