### ISSUE TITLE
The images stacking on top of one another (im using the image load plugin and have a fixed height)

### ISSUE THREAD

**Issue by ChrisKissoon** [giotiskl/Filterizr#82]
Hi Im using the filterizr plugin and when i click a category "grooms family" my layout is broken for the last row and the images get stacked. If you click on photos here: https://www.webdevtt.com/text/

you'll see the image going on top one another 

Solutions i've tried:
Setting
  var filterizd = $('.filtr-container').filterizr({
    layout: 'packed'
});
explicitly setting the image height
and 
using the imagesloaded plugin

Also the image looks great when all are displayed but breaks when i click the groom's family category. 
This is my last resort to get help. If someone can help it would be awesome.

**Comment by giotiskl** [comment]
@ChrisKissoon can you please try removing the rows and directly placing all of your filtr-items inside the grid?

**Comment by giotiskl** [comment]
@ChrisKissoon all issues should be solved in [v1.3.3](https://github.com/giotiskl/Filterizr/archive/1.3.3.zip), closing  for now. Let me know if otherwise.
