### ISSUE TITLE
Please help, I have install Filterizr with npm 

### ISSUE THREAD

**Issue by ploutos27** [giotiskl/Filterizr#83]
Hi. I'm struggling the last hour with one issue that unfortunately am not able to determine since i don't get any any error from my webpack.  After clicking on the data-filter categories nothing is change. I even move the filterizrSetup() outside of the class and try to run it as a manualy import but I'm getting error message ".filterizr is not a function" it seems like I miss something check the codee below. 

> Inside App.js i have include the followings. 

`import filterizr from 'filterizr';
import Filterizr from './modules/Filterizr';`

> My Filterizr.js includes the following code: 

```
import $ from 'jquery
class Filterizr {
  constructor() {
    this.menu = $("#navItems");
    this.filterizr = $(".filtr-container__row");
    this.filterizrMenu();
    this.filterizrSetup();
  }
    filterizrMenu() {
      this.menu.on('click', 'li', function() {
        $(this).addClass("filtr-active").siblings().removeClass("filtr-active");
      });
    }
    filterizrSetup() {
      this.filterizr.on('load', function() {
          var filterizd = $(this).filterizr();
      });
    }
  }

export default Filterizr;
```

**Comment by giotiskl** [comment]
Hello there,
when you do the default import from 'filterizr', bare in mind that it will import for you the jQuery object, extended with the Filterizr plugin.
Your Filterizr.js should look like this:
```
import $ from 'filterizr'; // Imports jQuery object extended with .filterizr function

class Filterizr {
  constructor() {
    this.menu = $("#navItems");
    this.filterizr = $(".filtr-container__row");
    this.filterizrMenu();
    this.filterizrSetup();
  }
    filterizrMenu() {
      this.menu.on('click', 'li', function() {
        $(this).addClass("filtr-active").siblings().removeClass("filtr-active");
      });
    }
    filterizrSetup() {
      this.filterizr.on('load', function() {
          var filterizd = $(this).filterizr();
      });
    }
  }

export default Filterizr;
```

now inside your `App.js` you simply need to import and instantiate your class like this:
```
import Filterizr from './modules/Filterizr';
...
new Filterizr();
```

if the controls are still not working there must be a problem with the selectors you're using and you might have to show me your HTML

**Comment by ploutos27** [comment]
Hi. Thank you for your quick anwser. :) 

I have attached the error included with home section. Please note that i have also updated constructor() id and change it to class. ( I thought that cause the problem but) am new with ES5/ES6 and I have confused... 
I would appriciated if you could help me :) 


> Error message:
`Uncaught TypeError: (0 , _filterizr2.default) is not a function
    at new Filterizr (App.js:11198)
    at Object.<anonymous> (App.js:10466)
    at __webpack_require__ (App.js:20)
    at App.js:63
    at App.js:66
Filterizr @ App.js:11198
(anonymous) @ App.js:10466
__webpack_require__ @ App.js:20
(anonymous) @ App.js:63
(anonymous) @ App.js:66
18:59:59.978 
`

> Home Section:
`<section class="section__home-page">
          <ul class="navItems">
            <li class="filtr filtr-active" data-filter="all">All</li>
            <li class="filtr" data-filter="1">Residential</li>
            <li class="filtr" data-filter="2">Restoration</li>
            <li class="filtr" data-filter="3">Commercial</li>
            <li class="filtr" data-filter="4">Industrial</li>
            <li class="filtr" data-filter="5">Landscape</li>
            <li class="filtr" data-filter="6">Research</li>
            <li class="filtr" data-filter="7">Feature</li>
          </ul>

          <div class="filtr-container">
            <div class="filtr-item filtr-container__row--3" data-category="3" data-sort="value">
              <a href="assets/images/gallery/images/img-thumb-100.jpg" data-lightbox="3" class="hover08 hover14">
                <figure><img data-src="assets/images/gallery/thumbs/img-thumb-100.jpg" class="lazyload filtr-item__image" alt=""></figure>
              </a>
          </div>

          <div class="filtr-item filtr-container__row--3" data-category="1" data-sort="value">
            <a href="assets/images/gallery/images/img-thumb-99.jpg" data-lightbox="1" class="hover08 hover14">
              <figure><img data-src="assets/images/gallery/thumbs/img-thumb-99.jpg" class="lazyload filtr-item__image" alt="  "></figure>
            </a>
          </div>

          <div class="filtr-item filtr-container__row--3" data-category="1" data-sort="value">
            <a href="assets/images/gallery/images/img-thumb-98.jpg" data-lightbox="1" class="hover08 hover14">
              <figure><img data-src="assets/images/gallery/thumbs/img-thumb-98.jpg" class="lazyload filtr-item__image" alt="  "></figure>
            </a>
          </div>

          <div class="filtr-item filtr-container__row--3" data-category="1" data-sort="value">
            <a href="assets/images/gallery/images/img-thumb-97.jpg" data-lightbox="1" class="hover08 hover14">
              <figure><img data-src="assets/images/gallery/thumbs/img-thumb-97.jpg" class="lazyload filtr-item__image" alt=""></figure>
            </a>
          </div>

          <div class="filtr-item filtr-container__row--3" data-category="1" data-sort="value">
            <a href="assets/images/gallery/images/img-thumb-96.jpg" data-lightbox="1" class="hover08 hover14">
              <figure><img data-src="assets/images/gallery/thumbs/img-thumb-96.jpg" class="lazyload filtr-item__image" alt=""></figure>
            </a>
          </div>

          <div class="filtr-item filtr-container__row--3" data-category="7" data-sort="value">
            <a href="assets/images/gallery/images/img-thumb-95.jpg" data-lightbox="7" class="hover08 hover14">
              <figure><img data-src="assets/images/gallery/thumbs/img-thumb-95.jpg" class="lazyload filtr-item__image" alt=""></figure>
            </a>
          </div>

          <div class="filtr-item filtr-container__row--3" data-category="6" data-sort="value">
            <a href="assets/images/gallery/images/img-thumb-94.jpg" data-lightbox="6" class="hover08 hover14">
              <figure><img data-src="assets/images/gallery/thumbs/img-thumb-94.jpg" class="lazyload filtr-item__image" alt=""></figure>
            </a>
          </div>
        </div>
      </section>`

**Comment by giotiskl** [comment]
Based on your HTML structure you're instantiating filterizr on the wrong html element it should be `this.filterizr = $(".filtr-container");` **and** not `this.filterizr = $(".filtr-container__row");`

**Comment by 12evgen** [comment]
@giotiskl  I tried to connect as you advised, but the error 'is not a function' still exists

**Comment by Luckyfella73** [comment]
I just had the same issue. While it worked fine using webpack 3 I now got this error message using webpack 4 for bundling. I was able to solve the issue importing _Filterizr_ like that:

`import filterizr from 'filterizr/dist/jquery.filterizr.min.js'`
