### ISSUE TITLE
[Feature Request] Loading Animation

### ISSUE THREAD

**Issue by bdthemes** [giotiskl/filterizr#84]
Hello, 

I am happy with Filterizr but if you add some extra features so it will become more attractive and popular.

Please look at here: https://tympanus.net/Development/GridLoadingAnimations/# Can you add this type animation for the grid when page load or click on filter?

**Comment by giotiskl** [comment]
@bdthemes this will come in the future out of the box, but for the time being in the newest version `2.1.0` there is now an `onInit` callback. You could render your own spinner and hide it within that callback when the gallery is ready to be rendered.

**Comment by giotiskl** [comment]
@bdthemes since v2.2.0 there's now officially a built-in loading animation. Consultant the documentation for more info https://yiotis.net/filterizr/#/documentation/vanilla/options
