### ISSUE TITLE
Multiple Select Lists targeting 2 sets of data

### ISSUE THREAD

**Issue by bradallenfisher** [giotiskl/Filterizr#85]
Referencing #81 

I am trying to set up 2 separate select options that target different data from the data-category. I had hoped that using the data-multifilter class in my select options would work for allowing me to define the multifilterLogicalOperator: 'and', option. 

I can't seem to get that to work... For instance if I choose altoona from select list 1 and students from select list 2 i don't want to see Behrend Students.

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Filterizr Demo - With jQuery in Bundle</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="index.css">

    <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="crossorigin="anonymous"></script>
    <script src="controls.js"></script>
    <script src="dist/jquery.filterizr.min.js"></script>

    <script>
    $(function() {
      var filterizr = $('.filtr-container').filterizr(
      //Default options
      options = {
         animationDuration: .05,
         callbacks: {
            onFilteringStart: function() { },
            onFilteringEnd: function() { },
            onShufflingStart: function() { },
            onShufflingEnd: function() { },
            onSortingStart: function() { },
            onSortingEnd: function() { }
         },
         controlsSelector: '',
         delay: 0,
         delayMode: 'progressive',
         easing: 'ease-out',
         filter: 'all',
         filterOutCss: {
            opacity: 0,
            transform: 'scale(0.5)'
         },
         filterInCss: {
            opacity: 0,
            transform: 'scale(1)'
         },
         layout: 'sameSize',
         multifilterLogicalOperator: 'and',
         selector: '.filtr-container',
         setupControls: true
      });

      $('.filtr-select1').on('change', function(event) {
         var val = $(event.currentTarget).val();
         filterizr.filterizr('filter', val);
      });
      $('.filtr-select2').on('change', function(event) {
         var val = $(event.currentTarget).val();
         filterizr.filterizr('filter', val);
      });
    });
    </script>

  </head>
  <body>

    <div class="container">

      <div class="row">
        <select class='filtr-select1'>
          <option data-multifilter="all" value="all" selected>all</option>
          <option data-multifilter="altoona" value="altoona">altoona</option>
          <option data-multifilter="behrend" value="behrend">behrend</option>
          <option data-multifilter="up" value="up">UP</option>
        </select>
      </div>

      <div class="row">
        <select class='filtr-select2'>
          <option data-multifilter="all" value="all" selected>all</option>
          <option data-multifilter="students" value="students">student</option>
          <option data-multifilter="lion" value="lion">lion</option>
          <option data-multifilter="campus" value="campus">campus</option>
        </select>
      </div>

      <div class="row push-down">
        <div class="filtr-container">
          <div class="col-xs-6 col-sm-4 col-md-3 filtr-item" data-category="altoona, students" data-sort="Altoona Students">
            <img class="img-responsive" src="img/city_1.jpg" alt="sample image">
            <span class="item-desc">Altoona Students</span>
          </div>
          <div class="col-xs-6 col-sm-4 col-md-3 filtr-item" data-category="behrend, students" data-sort="Behrend Students">
            <img class="img-responsive" src="img/nature_2.jpg" alt="sample image">
            <span class="item-desc">Behrend Students</span>
          </div>
          <div class="col-xs-6 col-sm-4 col-md-3 filtr-item" data-category="altoona, lion" data-sort="Altoona Lion">
            <img class="img-responsive" src="img/city_3.jpg" alt="sample image">
            <span class="item-desc">Altoona Lion</span>
          </div>
          <div class="col-xs-6 col-sm-4 col-md-3 filtr-item" data-category="behrend, lion" data-sort="Behrend Lion">
            <img class="img-responsive" src="img/industrial_1.jpg" alt="sample image">
            <span class="item-desc">Behrend Lion</span>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

```

**Comment by giotiskl** [comment]
The problem is that you're using the wrong method. In your `onchange` event for both selects try replacing this line: `filterizr.filterizr('filter', val);` to this `filterizr.filterizr('toggleFilter', val);`. Let me know how it works.

**Comment by bradallenfisher** [comment]
Thanks for your response... It sort of works... and I'm sure it's by design. I know this is an edge case request. 

So on a clean refresh of the page all items are shown.
I have 2 select items both set to ALL.
When i choose an option from the first select list I get the correct data shown.
When I choose an option from the second list I get the correct data shown.
However, after I have made both choices, I change my mind and change the second select list to a different option, no data is returned. I assume this is because, as designed, it is collecting (toggling rather than setting new values) the options as an on off value.

I guess the workaround would be to refresh the page, make the first choice again, then the new second choice...

**Comment by giotiskl** [comment]
@bradallenfisher you're correct. 

You could still make this work but it will require you to implement a bit of custom logic on your part.

When you click on a new value, the new value is toggled on, but the old value is not toggled off of course.

This means you would have to get the old value, call `toggleFilter` on it again to turn it off and then `toggleFilter` on the new value (after the change event) to reflect the change.

**Comment by bradallenfisher** [comment]
Thanks for your responses. Great project!!!

**Comment by narayananp** [comment]
How  to get the old value, call toggleFilter on it again to turn it off and then toggleFilter on the new value (after the change event) to reflect the change.
Coding example Please.

**Comment by narayananp** [comment]
@bradallenfisher , Can you please share the working code.

**Comment by bradallenfisher** [comment]
Sorry i didn't ever finish this one. We moved on to a new project.

**Comment by narayananp** [comment]
@giotiskl 
How to get the old value, call toggleFilter on it again to turn it off and then toggleFilter on the new value (after the change event) to reflect the change.
Coding example Please.

**Comment by narayananp** [comment]
$(function() {
      var filterizr = $('.filtr-container').filterizr(
   //Default options
      options = {
      animationDuration: .05,
      callbacks: {
      onFilteringStart: function() { },
      onFilteringEnd: function() { },
      onShufflingStart: function() { },
      onShufflingEnd: function() { },
      onSortingStart: function() { },
      onSortingEnd: function() { }
      },
      controlsSelector: '',
      delay: 0,
      delayMode: 'progressive',
      easing: 'ease-out',
      filter: 'all',
      filterOutCss: {
      opacity: 0,
      transform: 'scale(0.5)'
      },
      filterInCss: {
      opacity: 0,
      transform: 'scale(1)'
      },
      layout: 'sameSize',
      multifilterLogicalOperator: 'and',
      selector: '.filtr-container',
      setupControls: true
      });

      $('#ddlShape').on('change', function() {
         var val = $(this).val();
         filterizr.filterizr('$(function() {
      var filterizr = $('.filtr-container').filterizr(
   //Default options
      options = {
      animationDuration: .05,
      callbacks: {
      onFilteringStart: function() { },
      onFilteringEnd: function() { },
      onShufflingStart: function() { },
      onShufflingEnd: function() { },
      onSortingStart: function() { },
      onSortingEnd: function() { }
      },
      controlsSelector: '',
      delay: 0,
      delayMode: 'progressive',
      easing: 'ease-out',
      filter: 'all',
      filterOutCss: {
      opacity: 0,
      transform: 'scale(0.5)'
      },
      filterInCss: {
      opacity: 0,
      transform: 'scale(1)'
      },
      layout: 'sameSize',
      multifilterLogicalOperator: 'and',
      selector: '.filtr-container',
      setupControls: true
      });


	  
  $(".filtr-select1").on('change', function () {
         var val = $(this).val();
         filterizr.filterizr('toggleFilter', val);
    }).focus(function() {
        var previous = $(this).val();
		filterizr.filterizr('toggleFilter', previous);
    });
	
		  
  $(".filtr-select2").on('change', function () {
         var val = $(this).val();
         filterizr.filterizr('toggleFilter', val);
    }).focus(function() {
        var previous = $(this).val();
		filterizr.filterizr('toggleFilter', previous);
    });

    });

**Comment by gkrinc** [comment]
@narayananp you have to keep track of what's toggled yourself. I have radio buttons that represent the current filters. You could create a state variable as well. This isn't a great solution because there isn't a single source of truth, but it works.

Filterizr should have a way to get the list of currently applied filters.
