### ISSUE TITLE
Multiple Filter Gallery On Same Page

### ISSUE THREAD

**Issue by theharshin** [giotiskl/Filterizr#91]
If we use multiple instances of Filterizr on the same page, the filters are being applied to all the instances. For describing the issues more clearly, I've created a fiddle here: 
https://jsfiddle.net/theharsh/8tu6cr9q/

**Comment by giotiskl** [comment]
The approach taken is not going to work and also goes into unnecessary trouble.

In the same fiddle you sent me try updating your HTML to this:
```
<!-- DEMO 1-->
<ul class="demo1-filter">
	<li>
	    <a href="#" class="demo1-control" data-filter="1">FILTER 1</a>
	</li>
	<li>
            <a href="#" class="demo1-control" data-filter="2">FILTER 2</a>
	</li>
</ul>

<ul class="demo2-filter">
	<li>
	     <a href="#" class="demo2-control" data-filter="1">FILTER 1</a>
	</li>
	<li>
	     <a href="#" class="demo2-control" data-filter="2">FILTER 2</a>
	</li>
</ul>


<div class="demo1">
	<div class="filtr-item" data-category="1">
		Hello
	</div>
	<div class="filtr-item" data-category="1">
		Hi
	</div>
	<div class="filtr-item" data-category="2">
		How Are You
	</div>
	<div class="filtr-item" data-category="2">
		I'm fine
	</div>
</div>

<!-- DEMO2-->
<div class="demo2">
	<div class="filtr-item" data-category="1">
		Hello
	</div>
	<div class="filtr-item" data-category="1">
		Hi
	</div>
	<div class="filtr-item" data-category="2">
		How Are You
	</div>
	<div class="filtr-item" data-category="2">
		I'm fine
	</div>
</div>
```

and  your JavaScript to this:
```
var demo1 = $('.demo1').filterizr({
   controlsSelector: '.demo1-control'
});

var demo2 = $('.demo2').filterizr({
   controlsSelector: '.demo2-control' 
});
```

**Comment by mariakhn** [comment]
Hi @giotiskl 
I want to thank you for providing such useful plugin. I am using Vanilla javascript version to filter portfolio gallery for my one HTML site. It is working completely fine but when I added another instance on a page, controls of filter working interchangeably. I mean clicking on filter controls of one gallery also triggers another gallery. I have tried adding setupControls: false, controlsSelector: 'demo1' options but nothing seems working. I really don't get what I am missing here. Can you help me please?

Here is my created fiddle: https://jsfiddle.net/mariakhn/1c8xmksp/4/

Thanks so much

**Comment by FrogMustang** [comment]
> Hi @giotiskl
> I want to thank you for providing such useful plugin. I am using Vanilla javascript version to filter portfolio gallery for my one HTML site. It is working completely fine but when I added another instance on a page, controls of filter working interchangeably. I mean clicking on filter controls of one gallery also triggers another gallery. I have tried adding setupControls: false, controlsSelector: 'demo1' options but nothing seems working. I really don't get what I am missing here. Can you help me please?
> 
> Here is my created fiddle: https://jsfiddle.net/mariakhn/1c8xmksp/4/
> 
> Thanks so much

Here you go @mariakhn. I fixed it for you 😁. Your HTML was a bit off compared to the example provided above.
```HTML
<section class="demo1-section">
  <div class="filter-menu">
    <ul>
      <li> <a href="#" class="filtr-control1" data-filter="all">All</a> </li>
      <li> <a href="#" class="filtr-control1" data-filter="1">Primary</a> </li>
      <li> <a href="#" class="filtr-control1" data-filter="2">Light</a> </li>
      <li> <a href="#" class="filtr-control1" data-filter="3">Dark</a> </li>
    </ul>
  </div>

  <!-- Portfolio Items -->
  <div class="demo1">
    <div class="filtr-item" data-category="2">
      <div class="card bg-light">
      </div>
    </div>
    <div class="filtr-item" data-category="3">
      <div class="card bg-dark">
      </div>
    </div>
    <div class="filtr-item" data-category="1">
      <div class="card bg-primary">
      </div>
    </div>
  </div>
</section>

<section class="demo2-section">
  <div class="filter-menu">
    <ul>
      <li> <a href="#" class="filtr-control2" data-filter="all">All</a> </li>
      <li> <a href="#" class="filtr-control2" data-filter="1">Primary</a> </li>
      <li> <a href="#" class="filtr-control2" data-filter="2">Light</a> </li>
      <li> <a href="#" class="filtr-control2" data-filter="3">Dark</a> </li>
    </ul>
  </div>

  <!-- Portfolio Items -->
  <div class="demo2">
    <div class="filtr-item" data-category="3">
      <div class="card bg-dark">
      </div>
    </div>
    <div class="filtr-item" data-category="1">
      <div class="card bg-primary">
      </div>
    </div>
    <div class="filtr-item" data-category="2">
      <div class="card bg-light">
      </div>
    </div>
  </div>
</section>

<!-- Vendors -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/filterizr/2.2.4/vanilla.filterizr.min.js"></script>

```


This is the JS. you were setting the options separately. I put them in the constructor and it works.
```javascript
var filterizd1 = new Filterizr('.demo1', {
		layout: 'sameWidth',
		controlsSelector: '.filtr-control1',
	});

	var filterizd2 = new Filterizr('.demo2', {
		layout: 'sameWidth',
		controlsSelector: '.filtr-control2',
	});
```
