### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by mohammadayoub96** [giotiskl/Filterizr#95]
I included the js files,  but i think the controls should be buttons, not li. and buttons and hove some preference, so should have to make a css file for it and then we can include it our project or overright  it.

**Comment by giotiskl** [comment]
The controls are HTML agnostic, they can be buttons or whatever else you prefer. Also they care about is that the data attributes are set on the correctly (data-filter / data-multifilter etc), as presented on Filterizr's website.

**Comment by mohammadayoub96** [comment]
I think you should have to add some styles by default in style.css
and include buttons or buttons group instead of li.
and finally i should come with a css file as i mentioned above and it has to ready to inject into project after any one can overight the styles according to his requirement.

**Comment by giotiskl** [comment]
@mohammadayoub96 it's a decision by design to let the user define their own styles. Filterizr is not a CSS framework.

Regarding the integration problems you have, can you post some of your code so that I can inspect what might be the problem?

**Comment by mohammadayoub96** [comment]
But its confusing in this, a simple design can be added with just 3 to 4 lines of code. and buttons can be added insted of li.
It should be user friendly, how can he design if even can not integrate it into the project.

**Comment by mohammadayoub96** [comment]
Integration should be easy and then any one can make its design according to his requirements.  It would thank full to you if you make this easy to use.

**Comment by giotiskl** [comment]
@mohammadayoub96 it is very easy to use as evidenced by the 7.000 people who install and use it every month without problems.

I will stop commenting here unless you provide some code, so that I can inspect if and where there are any problems.

**Comment by mohammadayoub96** [comment]
If you give permission i would like to contribute to it.

**Comment by mohammadayoub96** [comment]
Ok i provide the code here

**Comment by giotiskl** [comment]
@mohammadayoub96 you can contribute by following the guidelines described in the contribution section and opening a Pull Request, which will then be evaluated, and potentially merged.

**Comment by mohammadayoub96** [comment]
![screenshot 64](https://user-images.githubusercontent.com/20210961/39822037-0e88633c-53c3-11e8-9b1d-d02a5cce2ae8.png)
I added markup and controls as follows, 
and js as follows
![screenshot 65](https://user-images.githubusercontent.com/20210961/39822087-2a9b8ff4-53c3-11e8-8ac3-3ea00b890963.png)

Now tell me what i have to do...

**Comment by mohammadayoub96** [comment]
[Templete HTML5 Bootstrap 4.zip](https://github.com/giotiskl/Filterizr/files/1988337/Templete.HTML5.Bootstrap.4.zip)
here are the project files please provide me with a valid solution
make it ready i will be very thank full to you, and will definitely contribute to this project.

**Comment by mohammadayoub96** [comment]
Demos in source file does not work
