### ISSUE TITLE
Active class not set on filter list

### ISSUE THREAD

**Issue by kemie** [giotiskl/Filterizr#98]
Filterizr works as expected,however, the active class is not applied to the current filter. I made a minimal test case:

https://codepen.io/kemie/pen/pVmOqB

**Comment by giotiskl** [comment]
Are we talking about the filter buttons? 

This is something that you need to handle, this functionality is not baked into Filterizr on purpose.

**Comment by kemie** [comment]
Yes. I thought it was part of it, since the demos all have it. my bad :)
