### ISSUE TITLE
Grid bugged on bootstrap 4

### ISSUE THREAD

**Issue by magicwatchs** [giotiskl/Filterizr#99]
Hey!

I am using your amazing framework into my website project, but i am having some troubles.
Your framework is totally ignoring my .portifolio-item{ margin-bottom:20px}, and the page body is and the size of the body is going way beyond the footer with a lot of white space!

here is the link( go to catalogo page) : http://saopedrovidracaria-com-br.umbler.net/

can anyone helpme? i really need this framework. I guess that the problem is my grids... but i catch this portifolio template into bootstrap page, so, its right..

**Comment by giotiskl** [comment]
Solved in [v1.3.5](https://github.com/giotiskl/Filterizr/releases/tag/1.3.5).
